### PR TITLE
log using WithValues for key=value formatted log messagse

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

**What this PR does / why we need it**:
Right now we are logging WithName for key/value log messages. We should use WithValue which was meant for key/value formats. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akutz** [comment]
Hi @andrewsykim,

Are we sure `WithValues` is the same as `WithName`? Per the [GoDocs](https://godoc.org/github.com/go-logr/logr):

```golang
    // WithValues adds some key-value pairs of context to a logger.
    // See Info for documentation on how key/value pairs work.
    WithValues(keysAndValues ...interface{}) Logger

    // WithName adds a new element to the logger's name.
    // Successive calls with WithName continue to append
    // suffixes to the logger's name.  It's strongly reccomended
    // that name segments contain only letters, digits, and hyphens
    // (see the package documentation for more information).
    WithName(name string) Logger
```

It sure seems like `WithName` has a different distinction. But, then again, the go-logr `Logger` interface is just that, an interface. Looking at an implementation in the controller-runtime's [`DelegatingLogger`](https://github.com/kubernetes-sigs/controller-runtime/blob/ab6131a999ca9e6ff5bf83dba70dc7751751135f/pkg/log/deleg.go#L36-L62), it also appears that `WithName` initializes separate fields than the values:

```golang
// WithName provides a new Logger with the name appended
func (p *loggerPromise) WithName(l *DelegatingLogger, name string) *loggerPromise {
	res := &loggerPromise{
		logger:       l,
		name:         &name,
		promisesLock: sync.Mutex{},
	}

	p.promisesLock.Lock()
	defer p.promisesLock.Unlock()
	p.childPromises = append(p.childPromises, res)
	return res
}

// WithValues provides a new Logger with the tags appended
func (p *loggerPromise) WithValues(l *DelegatingLogger, tags ...interface{}) *loggerPromise {
	res := &loggerPromise{
		logger:       l,
		tags:         tags,
		promisesLock: sync.Mutex{},
	}

	p.promisesLock.Lock()
	defer p.promisesLock.Unlock()
	p.childPromises = append(p.childPromises, res)
	return res
}
```

**Comment by andrewsykim** [comment]
Name is what you see prefixed in a log line, but I don't think it makes sense to use names like `namespace=%s`.  

Also worth mentioning in the comments:
```
    // WithName adds a new element to the logger's name.
    // Successive calls with WithName continue to append
    // suffixes to the logger's name.  It's strongly reccomended
    // that name segments contain only letters, digits, and hyphens
    // (see the package documentation for more information).
    WithName(name string) Logger
```

**Comment by akutz** [comment]
Hi @andrewsykim,

> Name is what you see prefixed in a log line, but I don't think it makes sense to use names like namespace=%s.

I merely copied from CAPA. However, I agree that it violates the commented guidelines. I also maintain that the information is necessary due to the fact that each log entry about a resource benefits from describing the resource's provenance. This is in line with the way CAPV logged items in v1a1. 

This PR doesn't address either though. If you would like to avoid using special chars in `WithName` then please close this PR and open a new one that brings the loggers back in line with the way were initialized in v1a1. For example:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/64600d54f5427a3cd5b14e794aab0530469a9880/pkg/cloud/vsphere/context/cluster_context.go#L103

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/64600d54f5427a3cd5b14e794aab0530469a9880/pkg/cloud/vsphere/context/machine_context.go#L90

**Comment by andrewsykim** [comment]
will do! 

/close

**Pull request closed without merging**
