### PR TITLE
🌱 Bump CPI to v1.32.0-beta.1

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold
for tests  on https://github.com/team-cluster-api/cluster-api-provider-vsphere/pull/38

**Review by zhanggbj — APPROVED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
Verify doesn't matter, the last commit will be reverted once we have a new CPI release with a fix

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Review by zhanggbj — APPROVED** [review]
/lgtm

**Pull request merged**
