### PR TITLE
add v1alpha3 API types

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**: This PR is a split of #685. this adds the types first in.

**Which issue(s) this PR fixes** : Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akutz** [comment]
Hi @yastij,

Should #685 be closed for this?

**Comment by yastij** [comment]
Nope, this only contains the addition of the types,  #685 will do the actual switch in our code base

**Pull request merged**
