### PR TITLE
🌱 Rename e2e-image

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Just renaming the image we use in e2e tests to be ~ consistent how we do it in CAPI.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
(I'll look into the errors :))

**Comment by fabriziopandini** [comment]
lgtm pending ci fix

**Comment by sbueringer** [comment]
@fabriziopandini should be okay now

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
