### PR TITLE
[release-1.12] 🌱 Set base branch correctly for link checker

### PR DESCRIPTION
**Pull request by fabriziopandini**
Part of 1.12-rc.0 release tasks

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/hold
it seems that the PR is not getting all the jobs 🤔 
I will take a look tomorrow

**Comment by chrischdi** [comment]
> /hold it seems that the PR is not getting all the jobs 🤔 I will take a look tomorrow

Which jobs are you missing?

**Pull request merged**
