### PR TITLE
Fixes govc attach command

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
Adds the missing category flag `-c` in the failure domain proposal.

**Which issue(s) this PR fixes**:
n/a

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by gab-satchi — COMMENTED** [review]
/lgtm

**Comment by srm09** [comment]
/approve
minor doc change

**Pull request merged**
