### PR TITLE
[release-1.8] :seedling: Add ownerReference resilience test

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

(cherry picked from commit d63e2bcdebe6498f185ee11939c01a4aebd93c00)

Cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2209

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/test

**Comment by killianmuldoon** [comment]
/test pull-cluster-api-provider-vsphere-e2e-full-release-1-8

/hold
for CI

**Comment by killianmuldoon** [comment]
/retitle [release-1.8] :seedling: Add ownerReference resilience test

**Comment by chrischdi** [comment]
/lgtm

pending ci

**Comment by sbueringer** [comment]
Thx!

/approve

CI will block automatically. I really prefer our CAPV settings over what we have in core CAPI (manual triggered blocking jobs)

**Comment by killianmuldoon** [comment]
> I really prefer our CAPV settings over what we have in core CAPI (manual triggered blocking jobs)

I'll make that change if you want - seems better than the /hold /unhold dance.

**Pull request merged**
