### PR TITLE
Issue a clusterctl delete after e2e test

### PR DESCRIPTION
**Pull request by codenrhoden**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by akutz** [comment]
Hi @codenrhoden,

It appears that the `clusterctl` command is complaining about the flags?

**Comment by codenrhoden** [comment]
I haven't put any work yet into what the right way to do this was. I had just taken a quick stab at it then never came back to it. I'd have to run this "for real" on my own setup to figure it out.

**Comment by akutz** [comment]
Hi @codenrhoden,

FWIW, the reason this fails is because you need to use `--kubeconfig` to specify the path to the kubeconfig for the target cluster. The `-e` flag is just for the kubeconfig for the bootstrap cluster.

**Comment by akutz** [comment]
Hi @codenrhoden,

Is there anything I can do to help unblock you on this? Thanks!

**Comment by akutz** [comment]
Hi @codenrhoden,

e2e tests on master are working again. I'm going to point this PR back to `master` and hopefully you can find time to close the loop on this. If you can't, that's fine. Please let me know either way so I can reassign this to someone else. Thank you.

**Comment by codenrhoden** [comment]
yep, putting this on my stack.

**Comment by codenrhoden** [comment]
Hi @akutz and @andrewsykim,

I've finally given this a shot again. However, I must say I'm now very confused on exactly what `clusterctl delete cluster` is supposed do...

I ran the command that @akutz provided, and it failed at the end with this error:

```
F0925 16:59:18.734418   25483 delete_cluster.go:53] unable to finish deleting objects in bootstrap cluster, resources may have been leaked: error(s) encountered deleting objects from bootstrap cluster: [error deleting MachineDeployments: error deleting Clusters in namespace "": the server could not find the requested resource (delete machinedeployments.cluster.x-k8s.io), error deleting MachineSets: error deleting Clusters in namespace "": the server could not find the requested resource (delete machinesets.cluster.x-k8s.io), error deleting Machines: error deleting Clusters in namespace "": the server could not find the requested resource (delete machines.cluster.x-k8s.io), error deleting Clusters: error deleting Clusters in namespace "": the server could not find the requested resource (delete clusters.cluster.x-k8s.io)]
```

However, what is more interesting to me is what it actually did do. It started up a new KIND cluster (something I didn't expect) and deleted all the CAP* components from the target/management cluster. It did all of that successfully. But it didn't delete the K8s cluster. I'm left with a fully functional K8s cluster w/o CAPI. So I'm left wondering what the tool actually tries to accomplish.

When creating a cluster with `clusterctl`, it spins up kind, applies CAP* stack, uses that to create a cluster on vCenter, then "pivots" the KIND cluster into the cluster on vCenter. Upon issuing `delete`, I would have expected the tool to just delete the machines, taking the cluster with it. Instead, the tool is basically uninstalling CAPI. What's weird about that to me (even if that is the point), is that it spins up a new bootstrap cluster with KIND and moves all the clusters back to the "bootstrap" cluster (e.g. the new KIND cluster) instead of just deleting the resources with kubectl. I experimented with designating the mgmt cluster *as* the bootstrap cluster by using the `-e` arg, which I think should have worked to just install CAPI, but it just went into an endless loop (until I canceled it) and did nothing.

I really don't understand what the tool is for, apparently. It seems like it is for deleting *CAPI* clusters, the resource, and for deleting CAPI itself. It doesn't delete the *K8s* cluster (and physical/virtual resources associated) that was created via the pivot process.

Anyone have clarity on this?

**Comment by andrewsykim** [comment]
My current understanding of `clusterctl delete` is that it's only for deleting management clusters that were bootstrapped with `clusterctl`. If you tried to delete the cluster where CAPV is running, you can end up deleting the machine CAPV runs on, which could result in dangling resources. To avoid this, it pivots the CAPI specific resources back to the bootstrap cluster (on Kind) and then issues a delete to the cluster resource from there.

**Comment by codenrhoden** [comment]
> My current understanding of `clusterctl delete` is that it's only for deleting management clusters that were bootstrapped with `clusterctl`. If you tried to delete the cluster where CAPV is running, you can end up deleting the machine CAPV runs on, which could result in dangling resources. To avoid this, it pivots the CAPI specific resources back to the bootstrap cluster (on Kind) and then issues a delete to the cluster resource from there.

okay... I could see that working. And it almost did. But it doesn't. haha. I guess I'd have to dig deeper than open issues against CAPI. When I ran it, it successfully pivoted stuff back into the bootstrap cluster (kind), but then never deleted the machine resources in vCenter. no idea why.

**Comment by andrewsykim** [comment]
> but then never deleted the machine resources in vCenter. no idea why.

I think it's worth checking if at least clusterctl tried to delete the machine CRD, if it did then it's probably a CAPV issue, if it isn't then we can probably re-open this in CAPI

**Comment by codenrhoden** [comment]
> I think it's worth checking if at least clusterctl tried to delete the machine CRD, if it did then it's probably a CAPV issue, if it isn't then we can probably re-open this in CAPI

Okay, here is the [log](https://gist.github.com/codenrhoden/cd20b6703b771f094be608823e4de82a)

I think it's something CAPI/clusterctl. Here are the interesting bits:

* Moves the [cluster](https://gist.github.com/codenrhoden/cd20b6703b771f094be608823e4de82a#file-clusterctl-sh-L166-L179) definition from target to bootrap.
* Moves the actual [machine](https://gist.github.com/codenrhoden/cd20b6703b771f094be608823e4de82a#file-clusterctl-sh-L221-L249) definition. I think deleting this in the bootstrap cluster is what would take out the physical resource.
* Tries to [delete](https://gist.github.com/codenrhoden/cd20b6703b771f094be608823e4de82a#file-clusterctl-sh-L221-L249) the resources on the bootstrap cluster.

That last step fails. For some reason when it does the delete, it just gets a 404 not found. 🤷‍♂

**Comment by akutz** [comment]
Really dumb question @codenrhoden, but have you tried deploying:

1. Deploying a management cluster with CAPV `master` using `clusterctl`, then
2. Deploying a workload cluster from the new management cluster, then

**Comment by codenrhoden** [comment]
> Really dumb question @codenrhoden, but have you tried:
> 
> 1. Deploying a management cluster with CAPV `master` using `clusterctl`, then
> 2. Deploying a workload cluster from the new management cluster, then
> 3. Deleting the workload cluster with `kubectl delete cluster workload-cluster-1` (or whatever you named it)
> 
> Do the VMs for the workload cluster get removed? If so, then it's not a CAPV issue.

Yes and no. I did:

1. Deployed mgmt with CAPV and `clusterctl`. ✔️ 
2.Deployed workload cluster with `kubectl`. ✔️ 
3. Deleted workload cluster by doing `kubectl delete` in reverse order. (deleted machinedeployment, then controlplane, then cluster)

All machines were removed when expected in that scenario. Steps 1 and 2 were exactly as documented in the Getting Started guide.

**Comment by akutz** [comment]
Hmm. So deletion *should* propagate if we *just* delete the `Cluster` resource. I wrote some ITs on another project that validates that. If you have time, it may be worth trying the steps again, but once at step three, only delete the `Cluster` resource and verify the machines and VMs are removed as well.

**Comment by andrewsykim** [comment]
I thought we are using `clusterctl delete cluster` here because we only e2e test bringing up management clusters with clusterctl? 

> So deletion should propagate if we just delete the Cluster resource

This is true from my experience as well, though the kubecnofig secret is not deleted until we have CAPI v0.2.2 (see https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/588)

**Comment by akutz** [comment]
> I thought we are using `clusterctl delete cluster` here because we only e2e test bringing up management clusters with clusterctl?

Yes. I just wanted to verify the deletes worked at all, and deleting the workload cluster verifies CAPV *can* delete machines and their VMs.

> This is true from my experience as well, though the kubecnofig secret is not deleted until we have CAPI v0.2.2 (see #588)

That's not part of the scope of this particular issue though, since, as you said, we're only bringing up the initial management cluster with `clusterctl`. Once it is gone, so too will the secret be gone.

We're testing this to verify that `clusterctl delete` works as advertised. Although truth be told, now that `clusterctl` is owned by CAPI, I'm thinking it isn't really even necessary to validate this step. However, it's not a *bad* thing to do so either.

I personally would like to:

* Continue to attempt to delete the management cluster with `clusterctl delete`
* Record the exit code of that attempt
* Ensure all VMs are actually deleted with `govc vm.destroy`
* Exit the script with the exit code from `clusterctl delete`

**Comment by codenrhoden** [comment]
> Hmm. So deletion _should_ propagate if we _just_ delete the `Cluster` resource. I wrote some ITs on another project that validates that. If you have time, it may be worth trying the steps again, but once at step three, only delete the `Cluster` resource and verify the machines and VMs are removed as well.

I went ahead and tried that. It would be much easier. However, after 5 minutes so far, nothing has happened. and `kubectl` didn't return. weird.

```sh
$ kubectl -v 6 --kubeconfig=./out/management-cluster/kubeconfig delete -f ./out/trhoden-workload-cluster-1/cluster.yaml
I0925 18:15:51.778521    1853 loader.go:375] Config loaded from file:  ./out/management-cluster/kubeconfig
I0925 18:15:51.800124    1853 round_trippers.go:443] DELETE https://192.168.3.144:6443/apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters/trhoden-workload-cluster-1 200 OK in 11 milliseconds
cluster.cluster.x-k8s.io "trhoden-workload-cluster-1" deleted
I0925 18:15:51.839927    1853 round_trippers.go:443] DELETE https://192.168.3.144:6443/apis/infrastructure.cluster.x-k8s.io/v1alpha2/namespaces/default/vsphereclusters/trhoden-workload-cluster-1 200 OK in 39 milliseconds
vspherecluster.infrastructure.cluster.x-k8s.io "trhoden-workload-cluster-1" deleted
I0925 18:15:51.847012    1853 round_trippers.go:443] GET https://192.168.3.144:6443/apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters?fieldSelector=metadata.name%3Dtrhoden-workload-cluster-1 200 OK in 6 milliseconds
I0925 18:15:51.848591    1853 round_trippers.go:443] GET https://192.168.3.144:6443/apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters?fieldSelector=metadata.name%3Dtrhoden-workload-cluster-1&resourceVersion=2382&watch=true 200 OK in 0 milliseconds
I0925 18:17:05.454429    1853 round_trippers.go:443] GET https://192.168.3.144:6443/apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters?fieldSelector=metadata.name%3Dtrhoden-workload-cluster-1 200 OK in 2 milliseconds
I0925 18:17:05.456144    1853 round_trippers.go:443] GET https://192.168.3.144:6443/apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters?fieldSelector=metadata.name%3Dtrhoden-workload-cluster-1&resourceVersion=2588&watch=true 200 OK in 1 milliseconds

I0925 18:18:17.842618    1853 round_trippers.go:443] GET https://192.168.3.144:6443/apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters?fieldSelector=metadata.name%3Dtrhoden-workload-cluster-1 200 OK in 2 milliseconds
I0925 18:18:17.844258    1853 round_trippers.go:443] GET https://192.168.3.144:6443/apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters?fieldSelector=metadata.name%3Dtrhoden-workload-cluster-1&resourceVersion=2784&watch=true 200 OK in 0 milliseconds
I0925 18:19:51.595454    1853 round_trippers.go:443] GET https://192.168.3.144:6443/apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters?fieldSelector=metadata.name%3Dtrhoden-workload-cluster-1 200 OK in 2 milliseconds
I0925 18:19:51.597480    1853 round_trippers.go:443] GET https://192.168.3.144:6443/apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters?fieldSelector=metadata.name%3Dtrhoden-workload-cluster-1&resourceVersion=3038&watch=true 200 OK in 1 milliseconds
```

**Comment by akutz** [comment]
Hi @codenrhoden,

Your example shows you deleted the contents of `cluster.yaml`, which includes the `WCPCluster` as well. I'm not sure how that impacts things, but I was suggesting simply deleting the CAPI `Cluster` resource, by itself.

**Comment by andrewsykim** [comment]
@codenrhoden you can't `kubectl delete -f ./out/trhoden-workload-cluster-1/cluster.yaml` because that contains the `VSphereCluster` resource which the machine controller needs. 

To do a proper delete you have to delete the cluster resource only:
```
kubectl delete cluster trhoden-workload-cluster-1
```

**Comment by akutz** [comment]
Oops, didn't mean to gang up on @codenrhoden there, did we @andrewsykim? :)

I think if you explicitly deleted the objects in reverse, as @codenrhoden did in the first attempt, everything is fine. It's when you issue deletes simultaneously with no guaranteed order that the problem occurs.

**Comment by codenrhoden** [comment]
Oh, it's fine. I'm learning and making mistakes. haha. I just misinterpreted what was said. All good.

Regardless, I think we know that deleting machines within CAPV works fine and that clusterctl does not.

**Comment by codenrhoden** [comment]
I don't want to dig into it, as this PR is about the `clusterctl delete` action, but I did try the `kubectl cluster delete` the right way, and saw that only the control plane was removed:

```sh
[centos@centos capv]$ kubectl --kubeconfig=./out/trhoden-management-cluster/kubeconfig get machines
NAME                                               PROVIDERID                                       PHASE
trhoden-management-cluster-controlplane-0          vsphere://42305e52-681c-9026-d332-06e51ed93485   running
trhoden-workload-cluster-1-controlplane-0          vsphere://423041f2-d990-b1a2-3d20-2029689d6950   running
trhoden-workload-cluster-1-md-0-6bddc57557-nsdrp   vsphere://4230dda7-32df-5173-15d3-e47ed1431fe2   running

[centos@centos capv]$ kubectl --kubeconfig=./out/trhoden-management-cluster/kubeconfig delete cluster trhoden-workload-cluster-1
cluster.cluster.x-k8s.io "trhoden-workload-cluster-1" deleted
[centos@centos capv]$ kubectl --kubeconfig=./out/trhoden-management-cluster/kubeconfig get machines
NAME                                               PROVIDERID                                       PHASE
trhoden-management-cluster-controlplane-0          vsphere://42305e52-681c-9026-d332-06e51ed93485   running
trhoden-workload-cluster-1-md-0-6bddc57557-nsdrp   vsphere://4230dda7-32df-5173-15d3-e47ed1431fe2   running
```

@akutz I agree with you in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/475#issuecomment-535149159 about what we **should** do in the E2E test. I also wondered for a bit whether `clusterctl delete` was giving us any value, but it is supposed to work so we might as well test it!

**Comment by codenrhoden** [comment]
Just a quick update here...

Testing with `0.5.2-alpha` and the latest `clusterctl`, I can say that I no longer hit any issues with all the workload resources being deleted if I do a `kubectl delete cluster <workload-cluster-name>`. So that's good news.

Doing a `clusterctl delete` fails for me in the same way as described in: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/475#issuecomment-535133630.

Basically, after `clusterctl` pivots resources from the mgmt cluster to the bootsrap cluster, it fails when trying to delete those resources...

```
I1002 20:22:12.428481   30509 clusterdeployer.go:192] Deleting objects from bootstrap cluster
I1002 20:22:12.428506   30509 clusterdeployer.go:220] Deleting MachineDeployments in all namespaces
I1002 20:22:12.433284   30509 round_trippers.go:438] DELETE https://127.0.0.1:45463/apis/cluster.x-k8s.io/v1alpha2/machinedeployments 404 Not Found in 4 milliseconds
I1002 20:22:12.435425   30509 clusterdeployer.go:225] Deleting MachineSets in all namespaces
I1002 20:22:12.436342   30509 round_trippers.go:438] DELETE https://127.0.0.1:45463/apis/cluster.x-k8s.io/v1alpha2/machinesets 404 Not Found in 0 milliseconds
I1002 20:22:12.436406   30509 clusterdeployer.go:230] Deleting Machines in all namespaces
I1002 20:22:12.437122   30509 round_trippers.go:438] DELETE https://127.0.0.1:45463/apis/cluster.x-k8s.io/v1alpha2/machines 404 Not Found in 0 milliseconds
I1002 20:22:12.437186   30509 clusterdeployer.go:235] Deleting Clusters in all namespaces
I1002 20:22:12.437905   30509 round_trippers.go:438] DELETE https://127.0.0.1:45463/apis/cluster.x-k8s.io/v1alpha2/clusters 404 Not Found in 0 milliseconds
I1002 20:22:12.438034   30509 createbootstrapcluster.go:36] Cleaning up bootstrap cluster.
I1002 20:22:12.438058   30509 kind.go:70] Running: kind [delete cluster --name=clusterapi-e0558]
I1002 20:22:14.430687   30509 kind.go:73] Ran: kind [delete cluster --name=clusterapi-e0558] Output: Deleting cluster "clusterapi-e0558" ...
F1002 20:22:14.430726   30509 delete_cluster.go:56] unable to finish deleting objects in bootstrap cluster, resources may have been leaked: error(s) encountered deleting objects from bootstrap cluster: [error deleting MachineDeployments: error deleting Clusters in namespace "": the server could not find the requested resource (delete machinedeployments.cluster.x-k8s.io), error deleting MachineSets: error deleting Clusters in namespace "": the server could not find the requested resource (delete machinesets.cluster.x-k8s.io), error deleting Machines: error deleting Clusters in namespace "": the server could not find the requested resource (delete machines.cluster.x-k8s.io), error deleting Clusters: error deleting Clusters in namespace "": the server could not find the requested resource (delete clusters.cluster.x-k8s.io)]
```

**Comment by andrewsykim** [comment]
Some of the discussions in https://github.com/kubernetes-sigs/cluster-api/pull/1445 might be related

**Comment by akutz** [comment]
/close

No longer needed with new test framework.

**Pull request closed without merging**
