### PR TITLE
add quotes around a value in aggregate_label_role_patch.yaml file

### PR DESCRIPTION
**Pull request by AartiJivrajani**
**What this PR does / why we need it**:
This PR adds `""` around `true` in the `config/rbac/aggregate_label_to_cluster_role_patch.yaml` file. Without them, the `envsubst` was causing an error during `tilt up`. 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gab-satchi** [comment]
e2e failing for unrelated permission issues.
/approve
/lgtm

**Comment by srm09** [comment]
@AartiJivrajani Please rebase your branch and this should be ready to merge.

**Comment by AartiJivrajani** [comment]
Created another PR for this issue - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1381

**Pull request closed without merging**
