### PR TITLE
Match release tag script

### PR DESCRIPTION
**Pull request by akutz**
**What this PR does / why we need it**:
This patch adds a new script for matching a release tag.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
Related to #426

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akutz** [comment]
/assign @figo
/assign @codenrhoden 
/assign @frapposelli 

Could one of you please lgtm this? Thanks!

**Comment by akutz** [comment]
> /lgtm

Thanks @frapposelli. The test failures are confusing. Looks like Prow is drunk. This is a new file that has no links to anything, and I just added it to help support #426. Weird.

**Comment by frapposelli** [comment]
yeah, I couldn't see any correlation between this PR and the tests failing 😄, the script looks good so 👍

**Pull request merged**
