### PR TITLE
Backport: move datacenter defaulting to resource defaults

### PR DESCRIPTION
**Pull request by srm09**
Cherry pick of #1277 on release-0.7.

#1277: move datacenter defaulting to resource defaults

### CODE REVIEW

**Comment by srm09** [comment]
@schrej Would you be able to sign the CLA which should block this PR? This is a bug which blocks cluster creation in a multi Datacenter vCenter environment.

**Comment by schrej** [comment]
I've asked that someone takes care of the EasyCLA Corporate CLA, but I'm afraid that'll take while. But afaik EasyCLA is not enforced yet, and it shouldn't be blocking the merge. Or is it different for this project?

**Comment by yastij** [comment]
/approve
/lgtm

cla/linuxfoundation is passing

**Pull request merged**
