### PR TITLE
🌱 test: dump resources before ValidateResourceVersionStable test

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/3119/pull-cluster-api-provider-vsphere-e2e-supervisor-main/1815834140377878528

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-e2e-supervisor-main

Let it flake, ...

**Comment by chrischdi** [comment]
Wow, its actually the `EtcdMemberHealthy` condition which gets an updated `lastTransitionTime` 🤔 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/3120/pull-cluster-api-provider-vsphere-e2e-supervisor-main/1816751579517161472

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

(just merge when ready)

**Pull request merged**
