### PR TITLE
🌱 Make PowerOff move configurable when using vcsim

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
Make PowerOff move configurable when using vcsim

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
How is this implemented and used? (future PR?)

**Comment by fabriziopandini** [comment]
> How is this implemented and used? (future PR?)

Yes, but also a fix.
PowerOff mode was the only remaining hard-coded value in the list of settings that are included in the list of EnvVar and then used by templates, in this case for the upcoming tests for supervisor mode.

**Comment by sbueringer** [comment]
Okay got it. Was just surprised to see it as env var as it's not even configurable in the regular Cluster templates we publish (templates/* folder)

**Pull request merged**
