### PR TITLE
Updating GoLang version in Dockerfile

### PR DESCRIPTION
**Pull request by geetikabatra**
Currently Cluster-API release 0.3 uses Golang version 1.13.15 and
CAPV 0.7 uses 1.16.0. This PR updates the version so that CAPI
and CAPV are on sae version level.

Signed-off-by: Geetika Batra <geetikab@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by randomvariable** [comment]
Yes, v1alpha44 should be on 1.16

/lgtm
/approve

**Comment by randomvariable** [comment]
Main branch of this repo should match CAPI main, i.e. Go 1.16. Why are we attempting to revert this now?

**Comment by geetikabatra** [comment]
Closing this as rebasing would be a long process. The changes I did were in the master branch. Creating a new PR.

**Pull request closed without merging**
