### PR TITLE
docs: remove controlPlane version field for worker…

### PR DESCRIPTION
**Pull request by zdyxry**
**What this PR does / why we need it**:

When I read docs/getting_started.md, I was confused about how to judge the ControlPlane node. 

I saw this in the code:

```go
// HasControlPlaneRole returns a flag indicating whether or not a machine has
// the control plane role.
func (c *MachineContext) HasControlPlaneRole() bool {
	if c.Machine == nil {
		return false
	}
	return clusterUtilv1.IsControlPlaneMachine(c.Machine)
}
```

```go
// IsControlPlaneMachine checks machine is a control plane node.
func IsControlPlaneMachine(machine *clusterv1.Machine) bool {
	return machine.Spec.Versions.ControlPlane != ""
}
```

So maybe need delete this field when adding a worker node?

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by zdyxry** [comment]
I signed it

**Comment by akutz** [comment]
/close

There's a reason we're deferring the call to the upstream package. They've changed this check in v1a2. It used to be based on the version string, and now it is not.

**Comment by akutz** [comment]
/reopen

I'm an idiot and misunderstood the PR.

**Comment by akutz** [comment]
Thank you for this @zdyxry!

**Pull request merged**
