### PR TITLE
🌱 github: add workflow to auto-approve golangci-lint if ok-to-test label is set

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Manual cross-repo cherry-pick of 

- https://github.com/kubernetes-sigs/cluster-api/pull/9244

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
nit: Let's say merged and verified that it actually works :)

**Comment by chrischdi** [comment]
Note: 

- https://github.com/kubernetes-sigs/cluster-api/pull/9244

got merged.

**Review by killianmuldoon — COMMENTED** [review]
This worked for me in the CAPI implementation at https://github.com/kubernetes-sigs/cluster-api/pull/9251


Thanks for tackling this @chrischdi!

/lgtm
/approve
/hold

(for someone else to validate if they want)

**Comment by sbueringer** [comment]
Perfect!

Thx for confirming

/lgtm
/hold cancel

**Pull request merged**
