### PR TITLE
[release-1.9] ✨ Bump to Go 1.22.4

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Bumps to Go 1.22 to stay on a supported Go version

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Seems unrelated but let's see

/retest

**Comment by chrischdi** [comment]
/retest

propably related to maintenance in the CI env.

**Comment by chrischdi** [comment]
/retest

related to thumbprint change to sha256, changed back to sha1

/lgtm
/approve

**Pull request merged**
