### PR TITLE
:seedling: Re-enable LB network provider unit-tests

### LINKED ISSUE #1324: Re-enable LB network provider unit tests
**Describe the solution you'd like**
The supervisor [controller_test_suite](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vmware/test/controllers_suite_test.go#L76-L84) attempts to run the same test suite twice while toggling the suite parameter `isLB` to provision the `dummyLBNetworkProvider`

This issue is to re-enable those tests. The old way of calling `RunSpecs` twice won't work with Ginkgo. A couple of options: 
- turn isLB into a flag and call the same suite twice
- setup and teardown the manager for each test. During setup, the appropriate loadBalancer can be set

### PR DESCRIPTION
**Pull request by AectannArd**
**What this PR does / why we need it**:
It enables the unit test scenario with "DummyLBNetworkProvider" which was formally commented out.

**Which issue(s) this PR fixes**:
Fixes #1324

**Special notes for your reviewer**:

**Release note**:

### CODE REVIEW

**Comment by AectannArd** [comment]
@srm09 could you check this out, please

**Comment by AectannArd** [comment]
@vrabbi
@yastij 
Could you have a look, please?

**Comment by srm09** [comment]
@AectannArd Can you squash the changes?

**Comment by AectannArd** [comment]
Sure. Will do in a couple of hours

**Comment by AectannArd** [comment]
**vsphere_cluster_reconciler_test** seems to be particularly flaky (although I did not even touch it)

```
------------------------------
• Failure [30.435 seconds]
VIM based VSphere ClusterReconciler
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/controllers/vspherecluster_reconciler_test.go:49
  Reconcile delete
  /home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/controllers/vspherecluster_reconciler_test.go:247
    should remove legacy finalizer if present during the cluster deletion [It]
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/controllers/vspherecluster_reconciler_test.go:256
    Timed out after 30.001s.
              
    Expected
        <bool>: false
    to be true
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/controllers/vspherecluster_reconciler_test.go:355
```

**Comment by srm09** [comment]
> vsphere_cluster_reconciler_test seems to be particularly flaky
Yes it is on my list to fix it, I have observed those flakes myself.

**Pull request merged**
