### PR TITLE
Add new flags to generate-yaml

### LINKED ISSUE #359: QoL: Have generate-yaml.sh generate folders based on cluster name and type
/kind feature

**Describe the solution you'd like**
I would like generate-yaml.sh (any maybe, by extension - it's invocation method) to take a cluster name and type argument.

Valid types would be:

`prod, dev, ci`

Name would simply be the name applied to that K8s cluster when deployed, whether it's management or workload.

As an example: 

`hack/generate-yaml.sh -t ci -n workload-cluster-1`

This would output to the dir `./out/ci/workload-cluster-1`

Another example:

`hack/generate-yaml.sh -t prod -n mgmt-cluster-1`

This would output to the dir `./out/prod/mgmt-cluster-1`

**Anything else you would like to add:**
The first step would be to introduce these flags into `generate-yaml.sh` but ideally, whatever method is used to call it (currently `make prod-yaml`) would take this argument, I don't think the `Makefile` is ideal here, maybe it `generate-yaml.sh` just has another abstraction script or binary in front of it that handles image build and pushing along with handing off `yaml` generation.

**Environment:**

- Cluster-api-provider-vsphere version: 0.3.0-alpha.1
- Kubernetes version: (use `kubectl version`): 1.14.3
- OS (e.g. from `/etc/os-release`): macOS

### PR DESCRIPTION
**Pull request by akutz**
**What this PR does / why we need it**:
This patch adds new flags to the generate-yaml script.

* -c can be used to specify the name of the cluster
* -m is used to specify the name of the CAPV manager image

If -c is specified then the output directory becomes "./out/CLUSTER_NAME". If -o OUT_DIR is specified then the output directory is "OUT_DIR". Use -o to specify explicit output directories, otherwise the directories are unique based on the name of the cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #359 

**Special notes for your reviewer**: NA

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
* Adds -c CLUSTER_NAME and -m CAPV_MANAGER_IMAGE flags to generate-yaml.sh
```

### CODE REVIEW

**Comment by akutz** [comment]
Hi @mylesagray,

Please take a look.

/assign @andrewsykim,

This is ready for an lgtm IMO.

**Comment by akutz** [comment]
/assign @codenrhoden 

Maybe relevant to what you're doing as well?

**Comment by mylesagray** [comment]
LGTM

**Comment by akutz** [comment]
You’re okay with the lack of “type”? I figured since it really served no purpose, letting “out” be an override works the same way.

**Comment by codenrhoden** [comment]
/lgtm
/hold
hold is there just so @mylesagray can chime in on `type`. I think the way this is makes sense.

**Comment by mylesagray** [comment]
I agree, type is unnecessary- ship it.

**Pull request merged**
