### PR TITLE
add support for the kube-vip flavor

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**: This PR adds support for a kube-vip flavor, two env variables are introduced:

`CONTROL_PLANE_ENDPOINT_IP`: the VIP we want to use
`VIP_NETWORK_INTERFACE`: the network interface we want to bind the VIP to (e.g. `eth0`)

Pin dependencies to 0.3.7-rc.1 to allow envsubst to work

**Which issue(s) this PR fixes**: Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
add support for a kube-vip flavor
```

### CODE REVIEW

**Comment by thebsdbox** [comment]
Out of interest, this is referencing the `plnder` `kube-vip` image. Should it be referencing a `kube-vip` image hosted by VMware?

**Comment by randomvariable** [comment]
In the interests of transparency, it's best to rely on publicly available images not tied to any particular vendor I think?

**Comment by jayunit100** [comment]
is there a tracking issue for this to cross reference ? seems like a few folks are excited about it :)

**Comment by yastij** [comment]
closing in favour of #964

**Pull request closed without merging**
