### PR TITLE
🌱 csi: use images from new location

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/lgtm
/approve

Not sure if the e2e tests actually detect if CSI doesn't come up (I just don't remember the latest state on this)

**Comment by chrischdi** [comment]
> /lgtm /approve
> 
> Not sure if the e2e tests actually detect if CSI doesn't come up (I just don't remember the latest state on this)

They don't. Just want to make sure this is not wrong in some weird way

**Pull request merged**
