### PR TITLE
🌱 Drop WCP fault domains feature gate

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
I think the test is broken because it relied on the feature gate not being enabled, really nice..

**Comment by sbueringer** [comment]
CRD was not even deployed. So much about test coverage :)

**Comment by sbueringer** [comment]
@chrischdi Tests are green locally. Let's make sure we get this into the next CAPV beta, so folks can stop setting this env var

**Comment by chrischdi** [comment]
/lgtm
/approve

Also tests via CI are green.

**Pull request merged**
