### PR TITLE
replace featuregate flags to fix the e2e

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**: This PR fixes the CI by replacing the featureflag with explicit values, this is just a short-term fix until #922 merges

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/assign @ncdc 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ncdc** [comment]
You switched networks?

**Comment by yastij** [comment]
@ncdc - yes, seems like the one we're using was heavily used, so switched to a dedicated one

**Pull request merged**
