### PR TITLE
:seedling: Bump CPI version to v1.2.1

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>

**What this PR does / why we need it**:
Bump vSphere cloud provider to v1.2.1 which contains some bug fixes. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by andrewsykim** [comment]
oops forgot to push the image

/retest

**Comment by andrewsykim** [comment]
Looks like we got a few green runs now based on the latest 1.2 branch. Will update this PR with the official image once we cut the tag

**Comment by andrewsykim** [comment]
@yastij @randomvariable got a few green builds now based on the offfical v1.2.1 image. PTAL :)

**Comment by randomvariable** [comment]
Thanks for the fast turnaround!
/lgtm

**Review by yastij — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
