### PR TITLE
🌱 Remove keep alive feature

### PR DESCRIPTION
**Pull request by zhanggbj**
**What this PR does / why we need it**:
Keep alive is deprecated in current release and will be removed in future release. Please find more details in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2896
 
- Remove keep alive feature for CAPV govmomi mode
- Remove keep alive feature for CAPV supervisor mode e2e test

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #2945

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!
/lgtm
/assign @chrischdi 

/help ?

**Review by chrischdi — COMMENTED** [review]
I think we missed this two lines:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/277caf1e3b42f4778f01b4aa71b48d8ccc6b47b8/test/infrastructure/net-operator/controllers/networkinterface_controller.go#L40-L41

**Comment by zhanggbj** [comment]
@chrischdi thanks for catching it! Fixed.

**Comment by sbueringer** [comment]
Looks like the linter has an issue

**Review by chrischdi — COMMENTED** [review]
/approve

**Pull request merged**
