### PR TITLE
🌱 Bump to CPI v1.30.0-rc.0

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by fabriziopandini** [comment]
/lgtm
/approve

Nice to see the community rallying around the new K8s version!

**Comment by sbueringer** [comment]
Merging manually. We'll have to look into codecov (it's also failing on main)

**Pull request merged**
