### PR TITLE
✨ Bump CAPI to v1.8.1 and CPI to v1.31.0

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Testing https://github.com/team-cluster-api/cluster-api-provider-vsphere/pull/12

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/lgtm
/approve

/hold
for tests

**Comment by sbueringer** [comment]
Waiting for https://github.com/kubernetes/k8s.io/pull/7170

**Comment by chrischdi** [comment]
Tests are green

/hold cancel

**Pull request merged**
