### PR TITLE
:seedling: Bump Makefile dependency versions

### PR DESCRIPTION
**Pull request by killianmuldoon**
Bump dependencies for:

- envtest
- gotestsum
- conversion-gen
- yq
- govulncheck

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by MrDXY** [comment]
Hi, @killianmuldoon, I found the `make test` could fail on the master branch(locally executed on mac, not sure if this is only my case). But if I change the 
`export KUBEBUILDER_ENVTEST_KUBERNETES_VERSION ?= 1.28.0` to
`export KUBEBUILDER_ENVTEST_KUBERNETES_VERSION ?= 1.27.1` 
the test passes.

Also, the error message indicates: `unable to start control plane itself: failed to start the controlplane. retried 5 times: exec: "etcd": executable file not found in $PATH`.

Would you mind taking a quick look? Or maybe I should check my environment setup.

**Comment by killianmuldoon** [comment]
@MrDXY thanks for catching that - I have the version set outside my environment locally. 

Can you see if the changes in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2446 fix the issue for you?

**Comment by MrDXY** [comment]
I re-run `make test` locally, but the error persists. Also, I found a stack trace which may help resolve it. And I will double-check my environment settings tomorrow. Hope I didn't get you in the wrong direction.

```
------------------------------
[SynchronizedBeforeSuite] [FAILED] [0.008 seconds]
[SynchronizedBeforeSuite] 
/Users/dxinyuan/MrDXY/cluster-api-provider-vsphere/pkg/identity/identity_suite_test.go:74

  Timeline >>
  STEP: Creating new test environment @ 10/18/23 21:20:33.248
  [FAILED] in [SynchronizedBeforeSuite] - /Users/dxinyuan/MrDXY/cluster-api-provider-vsphere/pkg/identity/identity_suite_test.go:79 @ 10/18/23 21:20:33.256
  << Timeline

  [FAILED] Unexpected error:
      <*fmt.wrapError | 0x1400031f3c0>: 
      unable to start control plane itself: failed to start the controlplane. retried 5 times: exec: "etcd": executable file not found in $PATH
      {
          msg: "unable to start control plane itself: failed to start the controlplane. retried 5 times: exec: \"etcd\": executable file not found in $PATH",
          err: <*fmt.wrapError | 0x1400031f3a0>{
              msg: "failed to start the controlplane. retried 5 times: exec: \"etcd\": executable file not found in $PATH",
              err: <*exec.Error | 0x1400031f360>{
                  Name: "etcd",
                  Err: <*errors.errorString | 0x1400010a3e0>{
                      s: "executable file not found in $PATH",
                  },
              },
          },
      }
  occurred
  In [SynchronizedBeforeSuite] at: /Users/dxinyuan/MrDXY/cluster-api-provider-vsphere/pkg/identity/identity_suite_test.go:79 @ 10/18/23 21:20:33.256
------------------------------

```

**Comment by killianmuldoon** [comment]
Would be good to see what comes up as the command when you run `make test` let's maybe continue this conversation in slack though :sweat_smile: could you open a thread when you come back around to this?

**Pull request merged**
