### PR TITLE
Update CAPBK to v0.1.5

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

**What this PR does / why we need it**:
Update CAPBK to v0.1.5 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Update CAPBK to v0.1.5
```

### CODE REVIEW

**Comment by akutz** [comment]
Please update the PR with a release note, and then feel free to remove the hold.

**Comment by andrewsykim** [comment]
fwiw, we don't really parse the release notes there, we really should for generating CHANGELOG :)

**Comment by akutz** [comment]
> fwiw, we don't really parse the release notes there, we really should for generating CHANGELOG :)

We don't **yet**, but as you said, we should, and it's something I've wanted to do for a while. Given the desire, and the small time it takes to add them as we create PRs, it makes sense to have a populated backlog so we can verify the generation when we get around to it.

**Comment by andrewsykim** [comment]
>We don't yet, but as you said, we should, and it's something I've wanted to do for a while. Given the desire, and the small time it takes to add them as we create PRs, it makes sense to have a populated backlog so we can verify the generation when we get around to it.

+ 1000

**Pull request merged**
