### PR TITLE
🌱 test: bump ipam to v1beta1

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Finally bumps capi's ipam dependency in test to v1beta1.

We upgraded the ipam provider in the CI cluster which now allows us to do this.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by zhanggbj — APPROVED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
