### PR TITLE
Simplify package layout

### PR DESCRIPTION
**Pull request by akutz**
**What this PR does / why we need it**:
This patch simplifies the package layout by moving all of the packages located in `pkg/cloud/vsphere` directly into `pkg`. The previous layout is a vestigial artifact of when the providers all lived in a single repository, and that is no longer the case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

/assign @andrewsykim 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akutz** [comment]
Hi @vincepri / @ncdc,

I'd also appreciate your feedback on this PR. Thank you!

**Comment by ncdc** [comment]
For comparison, CAPA has pkg/cloud/..., CAPG has cloud (no pkg). I think it's largely up to you / we don't have consistency across the CAP* projects at the moment. This seems like a reasonable change.

**Comment by sidharthsurana** [comment]
looks like a reasonable change to me too
/lgtm

**Pull request merged**
