### PR TITLE
Create base images for bootstrap and manifests

### PR DESCRIPTION
**Pull request by codenrhoden**
**What this PR does / why we need it**:
Both the bootstrap and manifests container image install OS packages, and since
these images are built every time during E2E tests, that is time
consuming. We can speed this up by creating base images to build from,
only pulling in what is needed and not doing OS updates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by codenrhoden** [comment]
/assign @akutz 
When I was  debugging my issues with E2E yesterday, I noticed that a significant amount of time was spent building the manifests and bootstrap images. This was because they both do OS package installs. But those package installs don't change from run to run, so this could be done once in a base image that is re-used, speeding up E2E for us.

My plan here would be to:

 - have this PR merged
 - with this PR merged, build and push the base images
 - Open a new PR that consumes those base images

**Comment by akutz** [comment]
Hi @codenrhoden,

Love it. Thanks for this!

/lgtm
/approve

**Comment by codenrhoden** [comment]
@akutz The E2E test appears stuck again. Weird - second time in 24 hours. Last night I got it unstuck by doing a force-push, which killed and restarted the job. I'll wait a bit more, but if doesn't move along I may do that here. I'll fix the location of the `kustomize`binary and re-push. Then I think it would need another `/lgtm`. I've never done that after something went into the merge pool. 🤷‍♂  But hopefully none of that will be needed.

**Pull request merged**
