### PR TITLE
🌱 Prevent updating supervisors VSphereMachine.Spec.ResourcePolicyName

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Follow-up to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2566#discussion_r1439493539

/assign @srm09 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/lgtm

/assign @srm09 

Should this be also cherry-picked?

**Review by srm09 — COMMENTED** [review]
nit: Consider adding this check to the test at [VMOp machine reconcile test](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/032eda39c7d36609e0e7724557b309f028222473/pkg/services/vmoperator/vmopmachine_test.go#L291C4-L297C6)

/lgtm

**Comment by srm09** [comment]
> Should this be also cherry-picked?

Perfect candidate to cherry pick back to 1.8 and 1.7 since we backported the PR for the other ones too.

/hold if you wanna add the test as mentioned in the comment, otherwise remove the hold to proceed with the merge
/approve

**Comment by sbueringer** [comment]
Good catch. Yup let's add it to the unit test, we can merge tomorrow

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
