### PR TITLE
Add tests for the `services/govomi/metadata` package

### LINKED ISSUE #1472: Implement unit test cases for metadata package
/area testing

Implement unit tests for the public methods under the pkg/services/govmomi/metadata package. This package is mainly used to create tag/categories used when using the auto-tagging feature for `VSphereFailureDomain` objects.

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by ditsuke**
**What this PR does / why we need it**
Adds test cases for public methods from the metadata package. The metadata package's exposed methods are used in creating tags and tag categories for `VSphereFailureDomain` objects.
- [x] metadata.CreateCategory()
	Passed a valid metadata context, a category name and associable resource type the method should:
	- If a category with the same name doesn't already exist -- create a new category with a matching name and and associable resource type. The method should also return a valid non-empty category ID which can be used to reference the ID through the context's tag manager. 
	- If a category with the same name exists -- update the category by merging in any new associable resource type. The category ID returned must be the same as the existing category's ID.
- [x] metadata.CreateTag()
	Passed a valid metadata context, tag name and category ID this method should:
	- If a tag with the same name doesn't already exist -- create a new tag matching the name and category ID passed.
	- If a tag with the same name exists -- not do anything. The existing tag must not be mutated in any way.

**Which issue(s) this PR fixes**:
Fixes #1472

Signed-off-by: ditsuke <ditsuke@protonmail.com>

### CODE REVIEW

**Comment by ditsuke** [comment]
Feedback needed on the tests and whether ginkgo usage should be factored out. One point reviewers might be interested in is the test order matters here. With ginkgo v2 it would be simple to use the Serial decorator, but I assumed we might be okay with this behavior anyways since we're not parallelizing tests in the makefile. I can work on removing dependency on the test order if its a problem for us.

**Comment by geetikabatra** [comment]
There are lint errors in this patch. You need to run `make lint` and fix the errors.

**Comment by ditsuke** [comment]
@geetikabatra fixed with 87605de

**Comment by geetikabatra** [comment]
Hi @ditsuke, Could you add a little more context to the PR description. Like what do these functions(metadata.CreateCategory(), metadata.CreateTag()) do and what did you exactly try to test.

**Comment by ditsuke** [comment]
Hello @geetikabatra, I've updated the PR description with more relevant information. I hope this helps with review! I'll be happy to try and add more information or improve the new tests on feedback.

**Comment by ditsuke** [comment]
@aartij17 can we have an ok-to-test here too?

**Comment by srm09** [comment]
I would suggest removing the dependency of the tests being run serially. You could use the `govc category.create` command while building the VCSim object and then run the createTag tests.

**Comment by ditsuke** [comment]
@srm09 thank you for the pointer. I've refactored the tests to remove the serial run dependency. Ready for review again!

**Comment by geetikabatra** [comment]
Please squash all the commits.

**Comment by ditsuke** [comment]
> Please squash all the commits.

@geetikabatra done

**Comment by geetikabatra** [comment]
@yastij This one can be merged. Please take a final look. Thanks in advance.

**Pull request merged**
