### PR TITLE
Add rng-tools as default entropy gatherer to HAProxy

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:
Use of hardware entropy sources is less contentious than using haveged in #879 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
* Enable rngd for entropy gathering
```

### CODE REVIEW

**Comment by detiber** [comment]
/lgtm
/hold
holding for further review

Should we also be adding this to `image-builder` as well?

**Comment by randomvariable** [comment]
@detiber 
> Should we also be adding this to image-builder as well?

Yup. Gonna do it when I figure out how to build in ESXi

**Pull request merged**
