### PR TITLE
refractored find VM

### LINKED ISSUE #1435: Refactor method `findVM` in the `pkg/services/govmomi/util.go` file
/kind feature

**Describe the solution you'd like**
Improve unit testing for `pkg/services/govmomi/util.go`
This issue is a task for the broader issue: #1392 

Individual tasks for this issue:
- [ ] Break down `findVM` function to smaller functions `findVMWithBiosUUID`, findVMViaInventoryPath`
- [ ] Add unit tests for each of the broken down functions

**Anything else you would like to add:**
n/a

/area testing
/help
/good-first-issue

### PR DESCRIPTION
**Pull request by Prateeknandle**
Signed-off-by: Prateeknandle <prateeknandle@gmail.com>

**What this PR does / why we need it**:
In this pr we have refractored `findVM` function, into `findVMWithBiosUUID`, and will also add uint test for it, currently not added.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1435 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by Prateeknandle** [comment]
I'll add test cases soon.

**Comment by srm09** [comment]
@Prateeknandle implementation seems to be what I had in mind, looking forward to the tests,

**Comment by geetikabatra** [comment]
@Prateeknandle Do you need help with the tests?

**Comment by srm09** [comment]
You will need to start a [VCSim](https://github.com/vmware/govmomi/tree/master/vcsim) object in the test code. The `helpers` package exposes a `VCSimBuilder` which can be used to build this object. Setting the VM option on the model used to build the VCSim object prepopulate the object with some dummy VMs. You can find the UUIDs of those VMs and use that.

In an ideal world there would have been a `Session` interface, so that we could mock the `Finder` methods. That would have eliminated the need for this setup in unit tests. But `govmomi` does not expose interfaces, instead implements concrete struct and methods on those structs which makes it difficult to mock them.

**Comment by geetikabatra** [comment]
@Prateeknandle I agree with @srm09 . You might want to start a VCSim, it will bring you more clarity.
For now, you can create a `context` like [this](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg%2Fservices%2Fgovmomi%2Futil_test.go#L38-L41). For `Bios UUID`, you might want to run a VCSim and use that `biosUUID` from there.

**Comment by ditsuke** [comment]
@Prateeknandle It might be helpful to look at existing usage of VCSim in tests. I have one in [#1475](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1475/files#diff-dff46c9b2599f81ac847baaee1f68e46ac7631e7597162b6ca38304c5e7b01e4R129-R148). PTAL

**Comment by Prateeknandle** [comment]
I'm sry for being late, i'm busy with some stuff, it might take some time, really sry for being late:(

**Comment by aartij17** [comment]
> I'm sry for being late, i'm busy with some stuff, it might take some time, really sry for being late:(

No problem @Prateeknandle! Thanks for the update :)

**Comment by Prateeknandle** [comment]
Sorry for the inconvenience, I'm actually bust with some work and can't complete this pr, therefore closing it.

**Pull request closed without merging**
