### PR TITLE
Updates Kube-vip image to v0.4.0

### LINKED ISSUE #1314: Move kube-vip to new init routine
/kind feature

**Describe the solution you'd like**
The current template for new clusters still uses `start` as arg for kube-vip. Upstream moved their default to `manage` a while back.
IIRC new features only work with manage, not with start (  @thebsdbox pls correct me if im wrong)

**Anything else you would like to add:**
https://kubernetes.slack.com/archives/CKFGK3SSD/p1637609003082700

**Environment:**

- Cluster-api-provider-vsphere version: current
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

### PR DESCRIPTION
**Pull request by omniproc**
Fixes #1314

- Upgraded to 0.4.0
- Added new / changed parameters and documentation
- Added new required capability NET_RAW see documentation at https://kube-vip.io/install_static/

### CODE REVIEW

**Comment by omniproc** [comment]
Hm I think the test pipe is broken.

> Cannot complete login due to an incorrect user name or password

**Comment by omniproc** [comment]
seems like all tests went fine. can someone approve so we can close this in 2021? :-)

**Comment by omniproc** [comment]
@yastij I think the pipe is broken again:

` [BeforeSuite] BeforeSuite 
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/test/e2e/e2e_suite_test.go:105
  Unexpected error:
      <*url.Error | 0xc00046e5d0>: {
          Op: "Post",
          URL: "https://vcenter.sddc-54-70-161-229.vmc.vmware.com/sdk",
          Err: <*net.OpError | 0xc0004802d0>{
              Op: "dial",
              Net: "tcp",
              Source: nil,
              Addr: <*net.TCPAddr | 0xc00046e5a0>{IP: "6F\xa1\xe5", Port: 443, Zone: ""},
              Err: <*poll.DeadlineExceededError | 0x3fa54e0>{},
          },
      }
      Post "https://vcenter.sddc-54-70-161-229.vmc.vmware.com/sdk": dial tcp 54.70.161.229:443: i/o timeout
  occurred `

**Comment by kuja53** [comment]
I have one point. Currently there is issue with hostAlias in the kube-vip pod definition. It not possible to create another master nodes when you bootstrap your cluster. First node bootstraps ok and behave ok. Second one immediately tries to connect to local kube-apiserver which leads to "Connection refused" on them, because local kube-apiserver is not leader and cannot serves the API. I make a lot of tests on my local dev environment on Ubuntu 20.04 OVA template with baked kube-vip images. On v0.3.5 everything works except the defining different port for API :(

**Comment by srm09** [comment]
@kuja53 Are you saying that this is a blocker in case of having multiple CP nodes in the cluster? I can add a quick test which creates a HA Control Plane for the CAPV cluster and have some verification in place for `kube-vip`.

**Comment by kuja53** [comment]
@srm09 Hi, its little bit complicated. If you keep port on default value and have reasonable network connection between master cluster and newly created cluster, everything is fine. But If you will change port inside kube-vip definition. You need to change localAPIEndpoint in both init and join configurations. If you will change port only on kube-vip, kube-apiserver will not find it.

**Comment by srm09** [comment]
@omniproc could you rebase the branch? The CI issues have been fixed now, we can get this one merged now.

**Comment by srm09** [comment]
@kuja53 Would it make sense to enhance the cluster templates to include setting a custom port for the API server. That way we can include all the changes required for custom API server ports to be configurable via the same variable?

**Comment by omniproc** [comment]
@srm09 
rebase done. waiting for pipe to finish tests.

**Comment by omniproc** [comment]
@srm09 seems good now, all tests passed. LGTM label is missing but that's it.

**Pull request merged**
