### PR TITLE
[release-1.10] ✨ test/e2e: use vSphere projects from Boskos

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Manual, minimal cherry-pick of #3034

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
/hold

I'll re-trigger all tests after the CAPI relase

**Comment by sbueringer** [comment]
This test fails independent of this pr: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-e2e-supervisor-release-1-10-1-29-1-30

We should investigate, but it should not block this pr

**Comment by sbueringer** [comment]
/override pull-cluster-api-provider-vsphere-e2e-supervisor-upgrade-1-29-1-30-release-1-10 
/hold cancel

**Pull request merged**
