### PR TITLE
🌱 Bump sigs.k8s.io/cluster-api to v1.8.2

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

CI automatically uses CAPI v1.8.2 which lead to failures and requires e2e fixes from:
https://github.com/kubernetes-sigs/cluster-api/pull/11136/files#diff-ddb199a962dbc0b01aef54bdb65e0375a2ed58262d0b5999d50c7e70596496b5

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/lgtm
pending tests

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
