### PR TITLE
Updates CAPI to v1.2.2

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
Updates CAPI version to v.1.2.2
This was required to pull in a test update that triggers MachineDeployment rollout using ClusterClass.

**Which issue(s) this PR fixes**:
Fixes n/a

**Special notes for your reviewer**:
n/a

**Release note**:
```release-note
Update CAPI version to v1.2.2
```

### CODE REVIEW

**Comment by srm09** [comment]
Added a new job to [test-infra ](https://github.com/kubernetes/test-infra/pull/27508) to trigger running tests via prow.

**Review by yastij — APPROVED** [review]
/approve

**Pull request merged**
