### PR TITLE
🌱 Bump to Go 1.20.8

### PR DESCRIPTION
**Pull request by zhanggbj**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
Can we also bump it in 

https://github.com/zhanggbj/cluster-api-provider-vsphere/blob/bump_go/Dockerfile#L18

and

https://github.com/zhanggbj/cluster-api-provider-vsphere/blob/bump_go/hack/ensure-go.sh#L22

:-)

**Comment by zhanggbj** [comment]
@chrischdi Thanks! (I just search & replace 1.20.7 :D )

**Comment by sbueringer** [comment]
Ah looks like we missed some places the last time

/lgtm
/assign @chrischdi

**Pull request merged**
