### PR TITLE
🐛 Drop caBundle from CRDs to support Kubernetes 1.31

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Context: https://github.com/kubernetes-sigs/cluster-api/pull/10972

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
I didn't drop them in vm-operator-v1.8.6-0-gde75746a.yaml yet. Let's do that only if we hit a problem

**Comment by chrischdi** [comment]
> I didn't drop them in vm-operator-v1.8.6-0-gde75746a.yaml yet. Let's do that only if we hit a problem

Should be fine as we don't upgrade it currently afaik

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
/override pull-cluster-api-provider-vsphere-e2e-supervisor-main

only resource version flake

**Comment by sbueringer** [comment]
@chrischdi Fast-forwarded the release-1.11 branch to latest main

**Pull request merged**
