### PR TITLE
🐛 Reorder PCI device attachment operation

### LINKED ISSUE #1749: Upgrading the VM hardware version is blocked by PCI device attachment
/kind bug

**What steps did you take and what happened:**
- Create a cluster with a `VSphereMachineTemplate` 
   - with PCI devices attached.
   - with virtual machine hardware version to the minimum required version (`vmx-17` and above)
- Machines/VMs using the above template cannot start up since the VM hardware version never gets upgraded.

**What did you expect to happen:**
- VMs hardware version is upgraded on the runtime and the PCI device attachment is successful

**Anything else you would like to add:**
CAPV attaches the PCI devices to the VM as part of the Clone VM task before upgrading the hardware version of the VM which is possible only via the Upgrade VM Hardware task, which is queued later in the VM reconcile loop. So, the cloning never really succeeds coz the PCI device attachment on a VM with hardware version < vmx-17 is not supported.

**Environment:**

- Cluster-api-provider-vsphere version: `v1.5.1`
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

/assign

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
This patch reorders the process of attaching PCI devices to the VM. Previously, the PCI devices were attached during the VM cloning operation, but the PCI device attachment requires a minimum hardware version of vmx-17.
Instead of forcing the template to be hardcoded with a minimum hardware version, CAPV introduced the capability of upgrading the hardware version of the VM post clone operation succeeds. This would mean that the PCI devices need to be attached after the upgrade hardware VM task is finished and the hardware version of the VM has been successfully upgraded to some compatible version specified by the user.

**Which issue(s) this PR fixes**:
Fixes #1749

**Special notes for your reviewer**:
The govmomi dependency has been updated to v0.30.2, which is the latest version released at this time, since v0.30.0 is necessary for unit test support for this reordering.

**Release note**:

```release-note
 Reorder PCI device attachment operation
```

### CODE REVIEW

**Comment by geetikabatra** [comment]
Needs rebasing, otherwise looks good to me.

**Comment by srm09** [comment]
Raising a manual cherry pick for this PR because of the merge conflicts above.

**Pull request merged**
