### PR TITLE
calico - 3.11, 3.6 seems wonky for me sometimes getting hung on cni-i…

### LINKED ISSUE #653: Update calico version to support K8s 1.16 API's
/kind bug

**What steps did you take and what happened:**
Because of some breaking API changes in 1.16 I had to modify a few things in the addons.yaml related to the calico deployment and daemonset in order for the management cluster to deploy and pivot properly. For the deployment and daemonset I changed extensions/v1beta1 to apps/v1 and also add a selector to the calico controller deployment.
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
vSphere 6.7u3
- Cluster-api-provider-vsphere version: 0.5.2
- Kubernetes version: (use `kubectl version`): 1.16
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jayunit100**
update calico YAMLs, creating issue now.

### CODE REVIEW

**Comment by yastij** [comment]
@jayunit100 - did you validate this with CAPV clusters ?

**Comment by jayunit100** [comment]
yeah, tested.  just rebased and modified this PR to use the exact 3.11 yaml (removed my comment from the top of it)

**Comment by jayunit100** [comment]
i updated this PR to include the paratemeterization

**Comment by figo** [comment]
/lgtm

do we tested kubernetes 1.15, 1.16, 1.17? thanks

**Pull request merged**
