### PR TITLE
[release-1.6] 🌱 Grouped CI related cherry-picks

### PR DESCRIPTION
**Pull request by chrischdi**
This is a manual cherry-pick of:

- #2180
- #2167
- #2172
  - only CI parts
- #2174
- #2211
- #2147
  - only CI parts partially
- removes `contrib/haproxy/openapi/docs` which is full of broken links.

### CODE REVIEW

**Comment by sbueringer** [comment]
Same as on 1.7. Fine apart from linkchecker

**Comment by chrischdi** [comment]
Uploaded the missing sha256 sum for photon-3-kube-v1.24.10.ova .

**Comment by sbueringer** [comment]
Nice fix! :)

/lgtm
/approve

**Pull request merged**
