### PR TITLE
Fixes panic while deployment zone deletion

### LINKED ISSUE #1424: Panic when deleting VSphereDeploymentZone
/kind bug

**What steps did you take and what happened:**
I created a VSphereFailureDomain and an associated VSphereDeploymentZone. The VSphereDeploymentZone was stuck in a failing state because it couldn't find the tagged resources. I tried deleting the VSphereDeploymentZone, but the kubectl delete command hung. I killed the process and the checked the pods. The capv-controller-manager was in a crash loop. The logs for the crash indicate a nil pointer deference in the vsphereDeploymentZoneReconciler

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1bb2233]

goroutine 658 [running]:
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vsphereDeploymentZoneReconciler.reconcileDelete.func1(0xc000192a40, 0xc0008f4601)
        /workspace/controllers/vspheredeploymentzone_controller.go:271 +0x33
sigs.k8s.io/cluster-api/util/collections.And.func1(0xc000192a40, 0x6)
        /go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.0/util/collections/machine_filters.go:38 +0x65
sigs.k8s.io/cluster-api/util/collections.newFilteredMachineCollection(0xc0008f8860, 0xc0008f4630, 0x6, 0x6, 0xc000192e01)
        /go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.0/util/collections/machine_collection.go:136 +0x8c
sigs.k8s.io/cluster-api/util/collections.Machines.Filter(0xc0008f4600, 0xc000a5bd60, 0x2, 0x2, 0xc00026aa10)
        /go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.0/util/collections/machine_collection.go:145 +0x65
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vsphereDeploymentZoneReconciler.reconcileDelete(0xc0005a2440, 0xc000b65800, 0x25b2f48, 0xc0002e36d0, 0xc00026a930, 0x0)
        /workspace/controllers/vspheredeploymentzone_controller.go:270 +0x1ab
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vsphereDeploymentZoneReconciler.Reconcile(0xc0005a2440, 0x259d518, 0xc0000c8cc0, 0x0, 0x0, 0xc000b6c520, 0x5, 0xc0000c8c00, 0x0, 0x0, ...)
        /workspace/controllers/vspheredeploymentzone_controller.go:148 +0x80d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0001deb40, 0x259d518, 0xc0000c8c90, 0x0, 0x0, 0xc000b6c520, 0x5, 0xc0000c8c00, 0x0, 0x0, ...)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001deb40, 0x259d470, 0xc0008ba800, 0x1fd6d20, 0xc000a03600)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001deb40, 0x259d470, 0xc0008ba800, 0x0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0009a43c0, 0xc0001deb40, 0x259d470, 0xc0008ba800)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:223 +0x425```

All of the machines currently defined in the management cluster are in a running state. The failure domain and deployment zones were never applied to any machines. 

**What did you expect to happen:**
I should be able to delete a failing deployment zone

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Cluster-api-provider-vsphere version: v1.0.2
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
This PR fixes a panic while deleting the deployment zone when machines are using it.

**Which issue(s) this PR fixes**:
Fixes #1424 

**Special notes for your reviewer**:
n/a

**Release note**:
```release-note
Fixes panic while deployment zone deletion
```

### CODE REVIEW

**Review by tenczar — APPROVED** [review]
LGTM Thanks

**Comment by srm09** [comment]
@vrabbi @yastij @MaxRink Can y'all take a pass at this PR? 
This fixes a bug the controller-manager failure when deleting VSphereDeploymentZones.

**Comment by MaxRink** [comment]
/lgtm
looks good for me, just took me a while to get all the testcases :smile:

**Pull request merged**
