### PR TITLE
Switch to using kube-vip templates in CI

### PR DESCRIPTION
**Pull request by gab-satchi**
- adds ip claim and release in the setup script

needs https://github.com/kubernetes/test-infra/pull/23155 merged first to get access to the IPAM 

/hold

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by randomvariable** [comment]
```
error: stat /root/ipam-conf/capv-services.conf: no such file or directory
vpn
Releasing IP claim
error: stat /root/ipam-conf/capv-services.conf: no such file or directory
```

**Comment by gab-satchi** [comment]
wasn't able to find the secret last time. Trying once more before reaching out to testing-ops

/test pull-cluster-api-provider-vsphere-e2e

**Comment by gab-satchi** [comment]
after giving permissions to the correct SA

/test pull-cluster-api-provider-vsphere-e2e

**Pull request merged**
