### PR TITLE
rename errorreason/message fields in vsphereMachine status

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**: This PR renames status fields related to errors reason and messages to match CAPI's expectation

**Which issue(s) this PR fixes** : Fixes #

**Special notes for your reviewer**:

/assign @akutz 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ncdc** [comment]
@yastij are you planning on doing conversion webhooks for v1alpha2 <-> v1alpha3?

**Comment by yastij** [comment]
it's on my queue, but I'm not sure I will get to it before v1alpha3

**Comment by ncdc** [comment]
We still need the conversion bits, but those can come in #749 (cc @noamran)

/lgtm
/approve

**Comment by ncdc** [comment]
Need to increase the golint timeout

**Comment by yastij** [comment]
@ncdc - I'll file a PR to bump these timeouts

/retest

**Pull request merged**
