### PR TITLE
🌱 test: change labels used for creating IPAddressClaims to not hit the 63 characters length limit

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2594/pull-cluster-api-provider-vsphere-e2e-conformance-ci-latest-main/1750934298652839936

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by chrischdi** [comment]
VMC issue:

>  - lastTransitionTime: "2024-01-27T07:08:26Z"
>    message: 'no compatible datastores found for storage policy: Cluster API vSphere
>      Storage Policy'
>    reason: CloningFailed
>    severity: Warning
>    status: "False"
>    type: InfrastructureReady

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2671/pull-cluster-api-provider-vsphere-e2e-blocking-main/1751138165072072704/artifacts/clusters/bootstrap/resources/quick-start-70cx1x/Machine/quick-start-pmdaql-cp-xbrhn-8cz64.yaml

**Comment by sbueringer** [comment]
Nice, again

**Pull request merged**
