### PR TITLE
🌱 [release-1.9] Bump CAPV to from v1.8.10 and v1.7.7 for upgrade tests

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Bumps CAPV to the latest v1.8.10 for upgrade tests, otherwise it fails using the SHA256 thumbprint.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
Thanks!
/lgtm
/approve

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
