### PR TITLE
🌱 Modify the template generation logic for CAPV templates

### LINKED ISSUE #1384: Modify the template generation logic for CAPV templates
/kind feature

**Describe the solution you'd like**
Currently, the template generation code for `kibe-vip ` based templates generates a ClusterResourceSet which installs the CPI/CSI on the workload cluster. The names of these resources created by the CRS are not dynamically generated. Hence if trying to reuse the same manifest template for different workload clusters results in the same secrets/config maps(used by the CRS) being updated. This could have unintended consequences when working with multiple clusters.

**Anything else you would like to add:**
It would be great if we could prefix the resources with the name of the cluster to enable reuse of the same templates for different workload clusters.

**Environment:**

- Cluster-api-provider-vsphere version: n/a
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by scdubey**
Prefixed the ClusterResourceSet resources with the name of the cluster 

**What this PR does / why we need it**:
This change will help to generate template that will enable the reuse of same templates for different workload clusters
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1384 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by scdubey** [comment]
I prefixed all CPI/CSI resources under ClusterResourceSet except [csi.vsphere.vmware.com](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/0cb991a39c8c130d7d909d9cac23e64171d7578f/pkg/services/cloudprovider/csi.go#L143)

**Comment by srm09** [comment]
/ok-to-test
Can you use the generated template to create a cluster?

**Comment by aartij17** [comment]
@scdubey You can use ` goimports -local sigs.k8s.io/cluster-api-provider-vsphere -w pkg/ packaging/` 
The lint tests would pass then :)

**Comment by srm09** [comment]
@scdubey Can you fix the lint errors and retry?

**Comment by srm09** [comment]
/retitle 🌱 Modify the template generation logic for CAPV templates

**Comment by srm09** [comment]
/close
Will reopen a new PR later

**Pull request closed without merging**
