### PR TITLE
✨ Bump Kubernetes to v1.32 and add new OVA's

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

- [x] Uploaded OVA's
- [x] CPI release
- [x] Bumped CPI in vsphere.yaml
- [x] Updated CPI templates

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by chrischdi** [comment]
/hold

For CI

**Pull request merged**
