### PR TITLE
🌱 Replace CAPI's clustercache tracker by the new clustercache

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Removes usage of the deprecated remote.ClusterCacheTracker and related functions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-e2e-vcsim-govmomi-main

E1025 12:40:30.036079       1 mux.go:452] "Failed to start WorkloadClusterListener" err="accept tcp [::]:20000: use of closed network connection" listenerName="default/ipclaim-qqmrhnp7xbhwnvwr4qmw9knxhpfgm2tl" address="https://10.244.0.12:20000"

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-e2e-vcsim-supervisor-main

failed before upgrade (CAPV 1.9.6)

**Comment by fabriziopandini** [comment]
/lgtm
@sbueringer for a final check

**Comment by sbueringer** [comment]
Tests on mirror are not green

**Comment by sbueringer** [comment]
/hold

Tests on mirror are consistently failing. I'll run them a few more times, but we'll probably have to debug them to figure out what's going on

**Comment by sbueringer** [comment]
Tests are all green

/hold cancel

**Pull request merged**
