### PR TITLE
Go modules

### PR DESCRIPTION
**Pull request by akutz**
This patch provides support for Go modules.

(Please note this PR is predicated on #267, and that this PR will be rebased once #267 is merged).

### CODE REVIEW

**Comment by sidharthsurana** [comment]
what is the version of go on the CI env? maybe that's why it is failing the tests?

**Comment by akutz** [comment]
Hey @figo and @frapposelli, it works. Many thanks to @figo for tracking down the issue to a version diff with the clusterctl dependencies.

**Comment by akutz** [comment]
Hi @frapposelli,

Can I get an "amen"? Or rather an approve? :)

**Pull request merged**
