### PR TITLE
🌱 Avoid adding watches after building controllers

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/approve

**Comment by chrischdi** [comment]
/lgtm

/hold

If others want to review but feel free to hold cancel

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
