### PR TITLE
OWNERS_ALIASES: Add yastij (Yassine Tijani) to maintainers list

### PR DESCRIPTION
**Pull request by randomvariable**
Nominating @yastij for promotion to the maintainers list as a significant contributor.

/hold

For lazy consensus for 7 days

### CODE REVIEW

**Comment by detiber** [comment]
+1 from me

On a related note, should we move some of the maintainers that are not currently active to emeritus status?

**Comment by ncdc** [comment]
> On a related note, should we move some of the maintainers that are not currently active to emeritus status?

+1. Same PR, or separate?

**Comment by detiber** [comment]
> +1. Same PR, or separate?

Either, just wanted to raise it since I had noticed it :)

**Pull request merged**
