### PR TITLE
[release-1.9] 🌱 Drop codecov from PRs

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
This only made it into main (before release-1.10 was created)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
I'll open PRs

**Comment by sbueringer** [comment]
Or not - the codecov action doesn't exist for <= release-1.8

**Pull request merged**
