### PR TITLE
🌱 Update docs to link to the OVAs in the community-owned GCS bucket

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by fabriziopandini** [comment]
@sbueringer  I found two other instances of https://storage.googleapis.com/ might be worth checking them as well
Also, should we do something to use new ova from our CI (also old branches)

**Comment by sbueringer** [comment]
> @sbueringer I found two other instances of https://storage.googleapis.com/ might be worth checking them as well Also, should we do something to use new ova from our CI (also old branches)

Thx. I'll take a look. 

CI fortunately doesn't download the images. We upload the images to the CI environment when we upload them to GCS. (so they are just available in vCenter)

**Comment by ameukam** [comment]
FYI, all GCS buckets `artifacts.*.appspot.com` will go away ultimately. There is no ETA for this.  We will have a communication about this.
Those are related to GCR and we want to migrate to Google Artifact Registry.

**Pull request merged**
