### PR TITLE
🌱 test: use ubuntu 24.04 in Runtime SDK test

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

This was missed in #3156

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by chrischdi** [comment]
/hold

Waiting for e2e at https://github.com/team-cluster-api/cluster-api-provider-vsphere/pull/16

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Comment by sbueringer** [comment]
/cherry-pick release-1.11

I think?

**Pull request merged**
