### PR TITLE
Set default e2e artifact folder

### PR DESCRIPTION
**Pull request by johananl**
**What this PR does / why we need it**:

Not having a default value for `--e2e.artifacts-folder` breaks the e2e tests when run locally (Prow overrides this flag with the `ARTIFACTS` env var).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

None

**Special notes for your reviewer**:

None

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by srm09** [comment]
Please rebase your branch and this should be ready to merge.

**Comment by johananl** [comment]
> Please rebase your branch and this should be ready to merge.

Done!

**Comment by srm09** [comment]
/lgtm
/approve

I have been adding it when manually adding this while running the e2e tests locally, no more! Thanks for the contribution.

**Pull request merged**
