### PR TITLE
🌱 Stop relying on GVK being set on regular typed objects

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Same as: https://github.com/kubernetes-sigs/cluster-api/pull/9956

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by zhanggbj — APPROVED** [review]
/lgtm

**Review by srm09 — COMMENTED** [review]
Can this be recorded in a doc some place for future instances when new controller/test code is being introduced so that this becomes a norm across the codebase.

/lgtm

**Comment by sbueringer** [comment]
@srm09 Not sure where to put it where someone actually reads it before making changes to the code base. It's unfortunately one of the many idiosyncrasies of using CR correctly :/

**Pull request merged**
