### PR TITLE
Add metadata field to the VSphereMachineTemplate

### PR DESCRIPTION
**Pull request by yastij**
**What this PR does / why we need it**: This API adds metadata to `VSphereMachineTemplate`, This is particularly needed for IPAM solution that add annotation to the template and expect it to trickle down to the machines

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/assign @srm09 @MaxRink 

**Release note**:

```release-note

```

### CODE REVIEW

**Review by yastij — COMMENTED** [review]
/approve

**Comment by MaxRink** [comment]
@yastij do we want to have that in alpha4 as well?

and /lgtm

**Comment by MaxRink** [comment]
ok, awesome

**Comment by yastij** [comment]
@MaxRink - we need to add some manual conversion here

**Pull request merged**
