### PR TITLE
build: Support arm64 images

### PR DESCRIPTION
**Pull request by jimmidyson**
**What this PR does / why we need it**:
This PR uses buildx to create multi-platform images, both for amd64
and arm64. This enables creating bootstrap clusters on Macs with M1
chips, which require pulling arm64 based images.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Support running CAPV controller manager on arm64
```

### CODE REVIEW

**Comment by geetikabatra** [comment]
I see tests failing in my local.
```
--- PASS: TestVmReconciler_WaitingForStaticIPAllocation/for_multiple_n/w_devices_with_DHCP_set_and_unset (0.00s)
    --- PASS: TestVmReconciler_WaitingForStaticIPAllocation/for_multiple_n/w_devices_with_static_IP_address_specified (0.00s)
    --- PASS: TestVmReconciler_WaitingForStaticIPAllocation/for_single_n/w_devices_with_DHCP4,_DHCP6_&_IP_address_unset (0.00s)
    --- PASS: TestVmReconciler_WaitingForStaticIPAllocation/for_multiple_n/w_devices_with_DHCP4,_DHCP6_&_IP_address_unset (0.00s)
=== RUN   TestRetrievingVCenterCredentialsFromCluster
I0406 13:55:48.586084   17747 vspherevm_controller.go:283] test/foo "msg"="vm is waiting for static ip to be available"
--- PASS: TestRetrievingVCenterCredentialsFromCluster (0.25s)
FAIL
FAIL	sigs.k8s.io/cluster-api-provider-vsphere/controllers	101.701s
```

@aartij17 could you trigger the tests here.

@jimmidyson Please try running the tests locally to validate this.
`make test`

**Comment by jimmidyson** [comment]
@geetikabatra There's a flake in the codebase - running `make test` a few times sometimes fails, sometimes passes, but I don't see how it can be related to this change which only changes the way the docker image is built, a docker image that is unused in the unit/integration tests run via `make test`.

**Comment by jimmidyson** [comment]
Also, the tests are run already - the status checks have passed... I'll re-run tests anyway. 

/test pull-cluster-api-provider-vsphere-test

**Comment by jimmidyson** [comment]
@geetikabatra Tests passed in CI again...

**Review by vrabbi — APPROVED** [review]
looks good and tests passed on my local.

**Comment by jimmidyson** [comment]
Thanks @vrabbi!

**Comment by MaxRink** [comment]
also looks good to me, just one thing i've noticed:
technically docker-push has a small behaviour change as it will now build the image if it did not exist before.
I don't think anyone relies on that behavior tho

**Comment by jimmidyson** [comment]
@yastij Any chance of an /approve on this please?

**Comment by jimmidyson** [comment]
Pretty please anyone? :sweat_smile:

**Review by yastij — APPROVED** [review]
/approve

**Comment by jimmidyson** [comment]
Tests are passing :tada: Could you /lgtm please @srm09?

**Pull request merged**
