### PR TITLE
:seedling: Improve API package dependency on controller-runtime

### PR DESCRIPTION
**Pull request by laozc**
**What this PR does / why we need it**:
This is to part of the work to address #2159 to remove dependencies on controller-runtime in API packages.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

**Comment by chrischdi** [comment]
I think that requires a `make generate-go-deepcopy generate-go-conversions` to fix the imports in the generated go files.

**Comment by sbueringer** [comment]
Thank you!!

/lgtm
/approve

**Pull request merged**
