### PR TITLE
🌱 add periodic Github job for trivy scanning

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

This PR adds a periodic github job to perform trivy scanning. This should help in surfacing any CVEs in the code base early in the cycle and can act as an early signal.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ykakarap** [comment]
I have tested the github workflow on my personal fork and it works. 
Run: https://github.com/ykakarap/cluster-api-provider-vsphere/actions/runs/4876844747/jobs/8700832316
Screenshot 2023-05-03 at 2 55 02 PM



The run on the `release-1.6` branch failed because the PR was not cherry-picked on the branch (the make targets were not available). It should start working after the PR is cherry-picked to the release branch.

**Comment by sbueringer** [comment]
@ykakarap This should not be cherry-picked. Per-branch stuff is only required on main. It will trigger it for all branches

**Comment by sbueringer** [comment]
Ah good point

**Comment by ykakarap** [comment]
The `make generate` target is adding `cluster-api` under categories for CRD `vspherevm` sometimes and it is not some other times. Just rerunning the target with no changes to the code is producing different result. Was able to reproduce this locally. Not sure why this is happening 🤔 

Rerunning the gen test for now to this PR.

/retest

**Pull request merged**
