### PR TITLE
🐛 CI: Introduces the thumbprint value in CI yaml

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
To unblock the CI tests on the `main` branch, we are providing this value from the `vsphere-ci.yaml`. More details in #1859 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes n/a

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by srm09** [comment]
/test pull-cluster-api-provider-vsphere-e2e
/override pull-cluster-api-provider-vsphere-test 
The prow job `pull-cluster-api-provider-vsphere-test` is being fixed in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1862

**Comment by srm09** [comment]
Manually adding lgtm to unblock the `main` branch
/approve

**Comment by sbueringer** [comment]
@chrischdi Do we need this on release-1.7 as well?

**Comment by chrischdi** [comment]
Nope, its already there on release-1.7 (via this MR)

**Pull request merged**
