### PR TITLE
📖 Remove unused parts from the PR template

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Follow-up to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2103#issuecomment-1655505707

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by sbueringer** [comment]
Duplicate of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2107

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Pull request merged**
