### PR TITLE
Add support for adding custom vmx keys

### LINKED ISSUE #919: Ability to set custom VMX keys in MachineDeployments
/kind feature

**Describe the solution you'd like**
As a cluster operator I want to manually allow some deployments to have transparent page sharing (whilst being aware of security concerns) by setting the sched.mem.pshare.salt value.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The specific use case is a subset of allowing the setting of arbitrary VMX keys on a VM after cloning.

**Environment:**

- Cluster-api-provider-vsphere version: N/A
- Kubernetes version: (use `kubectl version`):  N/A
- OS (e.g. from `/etc/os-release`):  N/A

### PR DESCRIPTION
**Pull request by EleanorRigby**
**What this PR does / why we need it**:
Adds support for configuring custom VMX keys.

  - vSphere supports adding [advanced configuration params](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.ConfigInfo.html#extraConfig) to VMX options in the clone-spec of VM. This PR enables vSphereMachineTemplate
  to accept `customVMXKeys` hash as spec param for the VM.

  - The custom VMX keys are added to extraConfig section of the clone-spec.

Custom VMX keys are used to change micro settings for a VM like, `pciPassthru.use64bitMMIO`.

**Which issue(s) this PR fixes** 
Fixes #919 

**Release note**:
```release-note
Adds support for configuring custom VMX keys on a vSphere VM
```

### CODE REVIEW

**Comment by EleanorRigby** [comment]
Tested by adding `disk.EnableUUID = "TRUE"` . It gets added to the VM 

Screen Shot 2020-08-24 at 10 07 22 PM

**Review by yastij — COMMENTED** [review]
/approve

I'll lgtm once I create the `release-0.7` branch and move this PR to it

**Comment by vrabbi** [comment]
Any updates on this being added?

**Pull request merged**
