### PR TITLE
:bug: Fixes issue that linked clone does not work

### LINKED ISSUE #1611: Not creating linked clone VMs
/kind bug

**What steps did you take and what happened:**
When creating linkedClone templates it doesn't seem to clone by linking even tho everything seems to point to it.

We notice this because cloning takes some time*, and I can also see that I can change the disk size in vmware (you shouldn't be able to for linked clones)

\* Compared to doing `govc vm.clone -link=true`, which is instant.

**What did you expect to happen:**
Cluster API creating a linked clone VM

**Anything else you would like to add:**

Spec:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: capi-quickstart
  namespace: default
spec:
  template:
    spec:
      cloneMode: linkedClone
      snapshot: root
      template: ubuntu-2004-kube-v1.23.5
      ...
```

capv-controller-manager log:
```
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.806536       1 vimmachine.go:146] capv-controller-manager/vspheremachine-controller/default/capi-quickstart-vq2cq "msg"="waiting for ready state"  
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.816881       1 util.go:86] capv-controller-manager/vspherevm-controller/default/capi-quickstart-bsx77 "msg"="using inventory path to find vm"  "path"="/testDatacenter/vm/devops/K8S/capi-quickstart-bsx77"
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.829771       1 clone.go:55] capv-controller-manager/vspherevm-controller/default/capi-quickstart-bsx77/vcenter "msg"="starting clone process"  
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.829793       1 clone.go:59] capv-controller-manager/vspherevm-controller/default/capi-quickstart-bsx77/vcenter "msg"="applied bootstrap data to VM clone spec"  
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.829821       1 template.go:64] capv-controller-manager/vspherevm-controller/default/capi-quickstart-bsx77/vcenter "msg"="find template by name"  "name"="ubuntu-2004-kube-v1.23.5"
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.887885       1 clone.go:80] capv-controller-manager/vspherevm-controller/default/capi-quickstart-bsx77/vcenter "msg"="linked clone requested"  
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.887910       1 clone.go:93] capv-controller-manager/vspherevm-controller/default/capi-quickstart-bsx77/vcenter "msg"="searching for snapshot by name"  "snapshotName"="root"
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.922744       1 clone.go:416] capv-controller-manager/vspherevm-controller/default/capi-quickstart-bsx77/vcenter "msg"="created network device"  "eth-card-type"="vmxnet3" "network-spec"={"networkName":"kubernetes_lab_infra_113","dhcp4":true}
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.928844       1 clone.go:271] capv-controller-manager/vspherevm-controller/default/capi-quickstart-bsx77/vcenter "msg"="cloning machine"  "cloneType"="linkedClone" "name"="capi-quickstart-bsx77" "namespace"="default"
capv-system/capv-controller-manager-558c4fc4fb-bnxlv[manager]: I0906 13:34:41.937704       1 request.go:1181] Request Body: {"metadata":{"resourceVersion":"473646"},"status":{"conditions":[{"lastTransitionTime":"2022-09-06T13:34:41Z","status":"True","type":"VCenterAvailable"},{"lastTransitionTime":"2022-09-06T13:34:41Z","reason":"Cloning","severity":"Info","status":"False","type":"VMProvisioned"}]}}
```

VSphereVM has correct properties:
```yaml
$ kubectl get vspherevms.infrastructure.cluster.x-k8s.io capi-quickstart-bsx77 -o yaml | grep -E "clone|snapshot"
  cloneMode: linkedClone
  snapshot: root
  cloneMode: linkedClone
  snapshot: snapshot-51414
```

The template contains the same snapshot ID as above:
```bash
$ govc snapshot.tree -vm ubuntu-2004-kube-v1.23.5 -i
[snapshot-51414]  root
[snapshot-51414]  .
```

It shouldn't be possible to change disk size for the VM, but it is (indicating it's not a linked clone):

image

On a real linked clone: ` govc vm.clone -link=true -vm ubuntu-2004-kube-v1.23.5 -snapshot=root test-linked-clone` (grayed out):
image

Also verified via `govc vm.info`, it's missing its "Parent" config:
```
            {
              "Key": 2000,
              "DeviceInfo": {
                "Label": "Hard disk 1",
                "Summary": "20,971,520 KB"
              },
              "Backing": {
                "FileName": "[DS_test2] capi-quickstart-bsx77/capi-quickstart-bsx77.vmdk",
                "Datastore": {
                  "Type": "Datastore",
                  "Value": "datastore-24"
                },
                "BackingObjectId": "",
                "DiskMode": "persistent",
                "Split": false,
                "WriteThrough": false,
                "ThinProvisioned": true,
                "EagerlyScrub": false,
                "Uuid": "6000C290-9907-bb6b-21bc-e755ca9980b3",
                "ContentId": "d4273b6348a1c3ff8a4ad023265f6adf",
                "ChangeId": "",
                "Parent": null,
                "DeltaDiskFormat": "",
                "DigestEnabled": false,
                "DeltaGrainSize": 0,
                "DeltaDiskFormatVariant": "",
                "Sharing": "sharingNone",
                "KeyId": null
              },
```

**Environment:**

- Cluster-api-provider-vsphere version: v1.3.1
- Kubernetes version: (use `kubectl version`): v1.24.0
- OS (e.g. from `/etc/os-release`): Ubuntu

### PR DESCRIPTION
**Pull request by ntoofu**
**What this PR does / why we need it**:

This PR fixes the issue that VMs are not cloned in linked clone mode regardless of the `cloneMode` in `VSphereMachineTemplate` manifest.

To clone VMs in linked-clone mode, `DiskMoveType` should be specified to `CreateNewChildDiskBacking`.
`DiskMoveType` appears in both `VirtualMachineRelocateSpec` and `VirtualMachineRelocateSpecDiskLocator` and the former is specified correctly, but as of now the later is specified to `MoveAllDiskBackingsAndDisallowSharing`, which is not compatible with linked clone.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #1611

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Fixes issue that linked clone does not work
```

### CODE REVIEW

**Comment by srm09** [comment]
/ok-to-test
Thanks for digging into this and submitting a fix.

**Comment by srm09** [comment]
/lgtm
Were you able to test this fix, unfortunately we do not have an upstream test for this one yet?

**Comment by ntoofu** [comment]
@srm09 Thank you for reviewing!

I tested manually, but did not record logs or screenshots. I built controller and container image from fixed source code, replaced CAPV controller running on local KinD cluster with it, deployed a node by using the new controller, and checked disk layout of the created VM with MOB (Managed Object Browser).

Since it is difficult to share the manual test result definitively, should I write a new test? If so, I will try to add a test to the `test/e2e` directory as integration with vCenter is required.

**Comment by srm09** [comment]
/approve
We should add an e2e test in a follow up PR, could you file an issue and start work on that one.

**Comment by srm09** [comment]
@ntoofu Could you rebase the PR on top of current `main`?

**Comment by ntoofu** [comment]
@srm09 I rebased this branch on the current `main` (4aafab65d5cfcde29026d01b70ca3065124cd019), and tried `/retest` but test still failed.
When I run `make verify-crds` on my local environment, I get no error.

I have no idea why this test fails. Could you give me some advice?

**Comment by ntoofu** [comment]
I realized the test is flaky.

I executed the following shell commands on my local `main` branch (4aafab65d5cfcde29026d01b70ca3065124cd019),

```
for i in {1..9}; do make verify-crds && echo "${i}: PASSED" >> results || echo "${i}: FAILED" >> results; sleep 5; done
```

and the result is:

```
1: FAILED
2: PASSED
3: PASSED
4: FAILED
5: PASSED
6: FAILED
7: PASSED
8: FAILED
9: PASSED
```

**Comment by ntoofu** [comment]
> We should add an e2e test in a follow up PR, could you file an issue and start work on that one.

I have written a test for verifying VMs are created as linked clone.

https://github.com/ntoofu/cluster-api-provider-vsphere/commit/a0f40823c5bfb4f34b34f963e8436b75d4ede3e3

I will create a new PR soon after this PR is merged.

**Comment by ntoofu** [comment]
> We should add an e2e test in a follow up PR, could you file an issue and start work on that one.

Follow up PR: #1766

**Pull request merged**
