### PR TITLE
Fix typo in template not found error

### PR DESCRIPTION
**Pull request by johananl**
**What this PR does / why we need it**:

Fixes a minor typo in an error string.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

None

**Special notes for your reviewer**:

None

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by invidian** [comment]
/lgtm

Blocked on #1343 it seems.

**Comment by srm09** [comment]
@johananl Rebase and this should be ready for merge

**Comment by johananl** [comment]
> @johananl Rebase and this should be ready for merge

Done!

**Pull request merged**
