### PR TITLE
🌱 Move ProviderServiceAccount & ServiceDiscovery controller to supervisor package

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold

have to check if all tests are still running

**Comment by sbueringer** [comment]
> have to check if all tests are still running

Number of tests are still the same, so we should be good. Now only waiting for test results on the mirror

**Comment by sbueringer** [comment]
/hold cancel

All tests green

**Comment by chrischdi** [comment]
/approve
/lgtm

/hold
in case you want to wait for fabrizio :-)

**Comment by sbueringer** [comment]
I think it should be pretty safe, so going ahead

/hold cancel

**Pull request merged**
