### PR TITLE
Update to image tag to v0.3.0-beta.0

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

**What this PR does / why we need it**:
Update release image tag to v0.3.0-alpha.2 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

/assign @akutz

### CODE REVIEW

**Comment by akutz** [comment]
/hold

Changing tag

**Comment by andrewsykim** [comment]
Updated to beta.0 as per our discussion

**Pull request merged**
