### PR TITLE
:warning:  Remove v1alpha3 and v1alpha4

### PR DESCRIPTION
**Pull request by killianmuldoon**
Remove the api types and related tooling related to the v1alpha3 and v1alpha4 apiVersions.

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2165

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/hold 

To broadcast in the community a bit more.

**Comment by chrischdi** [comment]
/hold
so you can unhold @killianmuldoon

**Comment by chrischdi** [comment]
Retriggered the codecov job... flaky unit/integration tests ...

**Pull request merged**
