### PR TITLE
Updates golang version to 1.15.8

### LINKED ISSUE #1140: Update golang version to 1.15 for release-0.7 branch
/kind feature

**Describe the solution you'd like**
We are moving the `main` branch to use golang version `1.15.8` and eventually to version `1.16.x` series. As part of this, we need to update the image versions used in the prow jobs (to use ones with golang 1.15+). Since we do not wanna add multiple jobs, each for a release version, it seems reasonable to move the `release-0.7` to use the newer golang version.

**Anything else you would like to add:**
n/a

**Environment:**
n/a

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
This patch updates the golang version to `1.15.8`

**Which issue(s) this PR fixes**:
Fixes #1140

**Special notes for your reviewer**:
n/a

**Release note**:
```release-note
Update underlying golang version to 1.15.8
```

### CODE REVIEW

**Comment by srm09** [comment]
Fixes #1140

**Comment by fabriziopandini** [comment]
FYI on CAPI we are on 1.16.0, and planning to move to 1.16.1 following main Kubernetes. 
Might be you want to jump directly to those version

**Comment by yastij** [comment]
I agree with @fabriziopandini - let's just go to 1.16.1

**Review by yastij — APPROVED** [review]
/approve

lgtm pending go version update

**Comment by srm09** [comment]
I had thought about this while upgrading the `main` branch to 1.16. During the work to upgrade that branch to 1.15, there were too many changes that needed to be made. I didn't wanna bundle too many changes into a single PR and make it difficult to merge. 
But y'all are right, maybe doing all the work in a single PR might make sense for this particular issue.

**Comment by yastij** [comment]
/lgtm

since we're trying to split he work into multiple PRs

**Pull request merged**
