### PR TITLE
Fix markdown tables in test/e2e/README.md

### PR DESCRIPTION
**Pull request by johananl**
This PR fixes a few issues with markdown tables in `test/e2e/README.md`.

### CODE REVIEW

**Comment by srm09** [comment]
Please rebase, the thumbprint was updated in the CI config which was merged in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1595
Maybe I should move that out to an external secret as well. Will raise a PR soon.

**Comment by srm09** [comment]
https://github.com/kubernetes/test-infra/pull/27168 moves the thumbprint logic over to an external secret instead of pulling it from a file.

**Comment by johananl** [comment]
Rebased. I'm not sure if you wanted me to change anything else following the two PRs you've mentioned @srm09. This PR only fixes Markdown style, i.e. I haven't touched the vars themselves.

**Comment by srm09** [comment]
The rebase was required to include the CI config changes, nothing else. It was needed for the e2e tests to pass.
/lgtm
/approve

**Pull request merged**
