### PR TITLE
Add addons.yaml into ci deployment

### PR DESCRIPTION
**Pull request by figo**
since we moved the CNI from cloud-init spec to addons

Signed-off-by: Hui Luo <luoh@vmware.com>

cc @andrewsykim @akutz

### CODE REVIEW

**Comment by akutz** [comment]
Hi @figo,

Is there anyway we can verify that this works? The VM we're using for e2e was deployed with Weave I imagine, so how are we validating that Calico is actually working?

**Comment by figo** [comment]
> Hi @figo,
> 
> Is there anyway we can verify that this works? The VM we're using for e2e was deployed with Weave I imagine, so how are we validating that Calico is actually working?

VM in e2e is vanilla ubuntu, so do not have any cni pre-builtin

**Comment by akutz** [comment]
> VM in e2e is vanilla ubuntu, so do not have any cni pre-builtin

Hi @figo,

Except we're not verifying anything about what's being stood up I thought? So how do we know CNI installed successfully?

**Comment by figo** [comment]
> > VM in e2e is vanilla ubuntu, so do not have any cni pre-builtin
> 
> Hi @figo,
> 
> Except we're not verifying anything about what's being stood up I thought? So how do we know CNI installed successfully?

yes, we are not verifying it right now,  we have discussed expanding e2e tests in other threads, but cni  need be part of deployment since it is core

**Comment by akutz** [comment]
So my question is how do we know the new CNI applied to the deployed cluster is working?

**Comment by akutz** [comment]
Also, CNI is not core except for the initial target cluster to which the management components are pivoted.

**Comment by figo** [comment]
@akutz  let me ask the question in this way, what do you suggest to change this PR?

**Comment by akutz** [comment]
I guess nothing. I just hoped we could verify that the new addon with the new CNI was working

**Pull request merged**
