### PR TITLE
✨ Add k8s v1.29.0 ova's

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Introduces kubernetes v1.29.0 ova's.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #2564

### CODE REVIEW

**Comment by chrischdi** [comment]
Uploaded fresh OVA's, the other ones were broken with some containerd issues.

/retest

**Comment by sbueringer** [comment]
PR looks good so far. I created a corresponding issue and one in CPI to track the work

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-e2e-full-main

Did pick the wrong version for clusterctl upgrade tests, because CAPV v1.8 (because of the templates) does/do not support v1.29 due to the kube-vip issues)

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-test-main

flake

**Comment by chrischdi** [comment]
e2e-full is very flaky (also on main / periodics :-( )


/test pull-cluster-api-provider-vsphere-e2e-full-main

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-e2e-full-main

**Review by fabriziopandini — COMMENTED** [review]
changes looks good!
looking forward to see the issue to be fixed in kube-vip!

/lgtm
/approve

**Comment by sbueringer** [comment]
@chrischdi Should we cherry-pick this PR and the follow-up fix PR to release-1.8?

**Pull request merged**
