### PR TITLE
🌱 Bump ccm to 1.28.0

### LINKED ISSUE #2203: Support Kubernetes 1.28
Kubernetes 1.28 will be released next week. To ensure it works with CAPV we have to do the following:
* Publish 1.28 OVA's
* Bump our e2e tests to test 1.28
  * PR for 1.27: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2016

We might have to keep cloud-provider-vsphere on 1.27 until they release 1.28. But I would then bump to cloud-provider 1.28 in a follow-up PR.

Opened an issue in the cloud-provider repo for v1.28: https://github.com/kubernetes/cloud-provider-vsphere/issues/750

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2203

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

/hold for ci

**Comment by chrischdi** [comment]
/hold cancel

because of tide doing its job

**Comment by sbueringer** [comment]
/test pull-cluster-api-provider-vsphere-e2e-full-main 

Just want to see if tide waits for e2e-full

**Pull request merged**
