### PR TITLE
only document latest Kubernetes patch versions

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

**What this PR does / why we need it**:
Given the recent Kubernetes CVE, I don't think there's much value in documenting OVAs for older Kubernetes versions 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by codenrhoden** [comment]
I think documenting just the latest images makes sense.

I'm not sure if I'd tie it to CVE's though. Meaning that even with just the two latest in the list now, the "older" version has the CVE, and newer one does not.

**Comment by andrewsykim** [comment]
Fine with me! Will update shortly

**Pull request merged**
