### PR TITLE
[release-1.5] 🌱 Bump golangci-lint to v1.53.3

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Manual cherry-pick of #2028 .

Older golangci-lint versions are way slower (especially the version which is/was used on release-1.5, `v1.47.3`. Resulting in false-positive failures of the linter.

This bumps to the latest version also used on main which does not have this issue.

This also fixes linter findings by aligning to the code of main.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Part of #2087

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sbueringer** [comment]
Not sure if this one will go away with restet :)

```
go: downloading github.com/google/uuid v1.3.0
/home/prow/go/pkg/mod/github.com/vmware/govmomi@v0.23.1/sts/signer.go:38:2: github.com/google/uuid@v1.3.0: missing go.sum entry for go.mod file; to add it:
	go mod download github.com/google/uuid
make[1]: *** [Makefile:67: bin/govc] Error 1
make[1]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/hack/tools'
make: *** [Makefile:[24](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2090/pull-cluster-api-provider-vsphere-test-release-1-5/1683873269905625088#1:build-log.txt%3A24)3: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/hack/tools/bin/govc] Error 2
```

**Comment by chrischdi** [comment]
> Not sure if this one will go away with retest :)
> 
> ```
> go: downloading github.com/google/uuid v1.3.0
> /home/prow/go/pkg/mod/github.com/vmware/govmomi@v0.23.1/sts/signer.go:38:2: github.com/google/uuid@v1.3.0: missing go.sum entry for go.mod file; to add it:
> 	go mod download github.com/google/uuid
> make[1]: *** [Makefile:67: bin/govc] Error 1
> make[1]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/hack/tools'
> make: *** [Makefile:[24](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2090/pull-cluster-api-provider-vsphere-test-release-1-5/1683873269905625088#1:build-log.txt%3A24)3: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/hack/tools/bin/govc] Error 2
> ```

Yep, but I didn't get it locally... now looking into it 🤔

**Comment by sbueringer** [comment]
I wonder if we fixed this somewhere (on another branch) by start installing govc without hack/tools/go.mod

**Comment by sbueringer** [comment]
Yeah we did this everywhere except on release-1.5. Let's cherry-pick the govc thing also to v1.5

**Comment by chrischdi** [comment]
> Yeah we did this everywhere except on release-1.5. Let's cherry-pick the govc thing also to v1.5

That's you, reading my thoughts 😂

**Comment by chrischdi** [comment]
these tests were too early.

/retest

**Pull request merged**
