### PR TITLE
crd: Disable preservation of unknown fields in v1alpha2

### PR DESCRIPTION
**Pull request by randomvariable**
Explicitly disable preservation of unknown fields to allow upgrade to v1 CRDs.

### CODE REVIEW

**Comment by yastij** [comment]
@randomvariable - e2e failures on v1a2 are expected, working on fixing them

**Comment by randomvariable** [comment]
```
+ kind create cluster --config /tmp/kind_config.yml
bash: line 31: /usr/local/bin/kind: Text file busy
bootstrapper VM ip: 192.168.2.17
govc: vm '' not found
+ EXIT_VALUE=1
```

**Pull request merged**
