### PR TITLE
redirect e2e.sh to ./scripts/e2e/e2e.sh

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**: This redirects `./hack/e2e.sh` used by the e2e prow job config into the actual e2e script for the 0.5 release branch

**Which issue(s) this PR fixes**: Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by randomvariable** [comment]
New error:
Complaint that the Docker client 1.41 is incompatible with the 1.40 daemon.

**Comment by randomvariable** [comment]
Taking this timed out getting to the provisioned API server? No obvious error message though

**Comment by yastij** [comment]
@randomvariable - we need to revisit the tests output for this branch later

/retest

**Pull request merged**
