### PR TITLE
Putting resources used by kustomization.yaml into its sub-folder

### PR DESCRIPTION
**Pull request by yuyangbj**
With kustomize PR 700 merged, in order to avoid attacking, all
resources are needed to saved in its sub-folder.

Fixes: #205

### CODE REVIEW

**Comment by yuyangbj** [comment]
I have  already sign the CLA, why it is still failed?

**Comment by frapposelli** [comment]
@yuyangbj CLA looks fine now

/ok-to-test

**Comment by figo** [comment]
@yuyangbj  thanks for the PR, kubebuilder requires `rbac` and `crds` under config, 
also we don't have to move them, kustomize suggest to use `bases` for none-local files, you do need to add kustomize.yaml in each folder, please refer to what been done at cluster-api main: https://github.com/kubernetes-sigs/cluster-api/blob/master/config/default/kustomization.yaml

**Comment by figo** [comment]
feel free to cancel the hold when you updated the PR, the current e2e test does not generate yaml from scratch, so can not catch the problem, we should address this soon.

**Comment by yuyangbj** [comment]
@frapposelli @figo thanks for the comments! I did not notice the kubebuilder problem in my local env, so I choose to keep resources there! Ok, I will use the bases to replace the resources and add kustomization.yaml in every folder.

**Comment by yuyangbj** [comment]
@figo I updated the PR, thanks!

**Comment by figo** [comment]
/lgtm 
we need to catch up on test part.

**Comment by frapposelli** [comment]
/lgtm

@sflxn PTAL and approve

**Comment by sidharthsurana** [comment]
> @yuyangbj Can you add the two key files that you copied to the .gitignore file so we don't accidentally check them into github in the future?

LGTM, once the .gitignore file is updated we can merge

**Comment by sflxn** [comment]
@yuyangbj Do you know whether Kustomize v1 compatible with these changes?  If not, can you create a new issue to update the makefile so it can detect kustomize version and warn users to update it?

**Comment by yuyangbj** [comment]
@sidharthsurana thanks for the review.

@sflxn I will update  the .gitignore and test the v1 again.

**Comment by yuyangbj** [comment]
@sflxn i tested, the makefile cannot work with kustomize v1 now because the secreteGenerator:files cannot be supported in V1. I want to use the 'kustomize version' to show version, but I got an error:
Version: {KustomizeVersion:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
I see it is an old issue in kustomize... so besides waiting the fix, any recommends for the workaround?

**Comment by sflxn** [comment]
@yuyangbj you don't have to deal with the makefile for this PR.  I was suggesting you open up another issue for the makefile changes.  For this PR, update this doc page with a note on Kustomize v2, https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/master/docs/self-service.

**Comment by yuyangbj** [comment]
@sidharthsurana @sflxn @frapposelli @figo done for a request changes, please review again.

**Pull request merged**
