### PR TITLE
🌱 Enable powerOffMode trySoft in cluster-templates and CI

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
We introduced powerOffMode in CAPV v1.8. We ensured that the default behavior doesn't change by using "hard" as default on the CRDs. 

I think it's reasonable now to start using trySoft in our cluster-templates and in CI. It's the ideal value and just changing the value in the cluster-templates doesn't break our API behavior in any way.

Also the VM's now have a chance to "return" their DHCP leases during shutdown, which is helpful for CI stability.

P.S. I don't want to cherry-pick this change as I don't want to change the field in cluster-templates in a CAPV v1.8 patch release

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/retest

/lgtm

**Comment by sbueringer** [comment]
/hold 
for CI

**Pull request merged**
