### PR TITLE
bump vSphere cloud provider  version to 1.2.0

### LINKED ISSUE #1002: Update vsphere cloud provider to v1.2.0
/kind feature

**Describe the solution you'd like**
vSphere cloud provider v1.2.0 has some good improvements / bug fixes we may want to pick up here. v1.2.0 should be compatible with any Kubernetes versions v1.1.0 supported. 

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by gwang550**
**What this PR does / why we need it**:
This PR bumps vSphere cloud provider version to v1.2.0 as it has some good improvements / bug fixes. v1.2.0 should be compatible with any Kubernetes versions v1.1.0 supported.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1002 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._
This PR changes vSphere cloud provider from v1.1.0 to v1.2.0
**Release note**:

```release-note
bump the CPI from 1.1.0 to 1.2.0
```

### CODE REVIEW

**Comment by andrewsykim** [comment]
Possibly a real failure, let's retest to check :) 

/retest

**Review by yastij — APPROVED** [review]
/approve

@andrewsykim @gwang550  - one question, are there any changes the resources (secrets, config etc...). Otherwise lgtm

**Comment by andrewsykim** [comment]
> @andrewsykim @gwang550 - one question, are there any changes the resources (secrets, config etc...). Otherwise lgtm

For v1.2.0 I don't think so, it was mostly bug fixes. @dvonthenen any thoughts here? For v1.18.0 coming up we probably do.

**Pull request merged**
