### PR TITLE
add well-known tolerations to released CAPV manager manifest

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

**What this PR does / why we need it**:
Adds toleration for well-known taints like node-role.kubernetes.io/master to released CAPV manager manifest.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes-sigs/cluster-api#1486

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Adds toleration for well-known taints like node-role.kubernetes.io/master to released CAPV manager manifest.
```

### CODE REVIEW

**Comment by andrewsykim** [comment]
> Please add this as a patch in the same dir.

Is this necessary if all variations of this will have this toleration?

**Comment by akutz** [comment]
> Is this necessary if all variations of this will have this toleration?

I only want to make sure we can replace `manager.yaml` with whatever upstream template gets updated over time. If the upstream template includes the toleration, then this is fine as is.

**Comment by andrewsykim** [comment]
Yeah this should be consistent with upstream - https://github.com/kubernetes-sigs/cluster-api/pull/1487

**Pull request merged**
