### PR TITLE
Updating "Getting Started" and "Troubleshooting" docs with image pull details

### PR DESCRIPTION
**Pull request by codyde**
**What this PR does / why we need it**:

I had numerous issues getting started with the CAPV provider, which were resolved by removing my existing manifest/manager images and pulling down updated ones. Chatting with @andrewsykim - he agreed this would be a good idea to PR into the Getting Started doc. I added additional clarity to the Troubleshooting doc to support as well.  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Documentation updates for consuming the provider. 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by codyde** [comment]
Update: Signed the CLA. Misunderstood the contributor guidelines on this, my apologies!

**Comment by andrewsykim** [comment]
Hi @codyde, a few linting errors from CI:
```
 docs/getting_started.md: 114: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs/troubleshooting.md: 204: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]

```

**Comment by codyde** [comment]
> Hi @codyde, a few linting errors from CI:
> 
> ```
>  docs/getting_started.md: 114: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
> docs/troubleshooting.md: 204: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
> ```

Fixed! Sorry about that!

**Comment by andrewsykim** [comment]
/approve

Looks great, one last thing - are you able to squash the last two commits "removing extra whitespace" with the previous commits?

**Comment by codyde** [comment]
Issues with this PR as a result of GIT problems. Closing PR and resubmitting per discussion with @andrewsykim

**Pull request closed without merging**
