### PR TITLE
🌱 Finalize CAPI v1.6.0-beta.1 bump & diagnostics implementation

### LINKED ISSUE #2356: Bump to CR v0.16
Just a tracking issue to collect things we should implement after the bump to CR v0.16

Most of them will be probably already documented in the migration doc (https://main.cluster-api.sigs.k8s.io/developer/providers/migrations/v1.5-to-v1.6)

Tasks:
* [ ] https://github.com/kubernetes-sigs/cluster-api/pull/9264

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2356

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/approve

/retest

**Comment by sbueringer** [comment]
@chrischdi Can you also lgtm? :) Not sure if there's anyone else around

**Comment by sbueringer** [comment]
/hold
Have to check something

**Comment by sbueringer** [comment]
Noticed a few other places where we didn't bump to v1.6.0-beta.1. Will run tests, verify metrics and then get back to you

**Comment by sbueringer** [comment]
Okay we're now getting metrics from all controllers in the e2e artifacts

/hold cancel

**Comment by sbueringer** [comment]
@chrischdi PTAL

**Review by chrischdi — COMMENTED** [review]
/approve

**Comment by sbueringer** [comment]
@fabriziopandini @chrischdi Someone has to give me an lgtm :)

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Pull request merged**
