### PR TITLE
🌱 Deprecate AutoConfigure functionality

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

Part of #1899

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by randomvariable** [comment]
Can  you update the release note? (or maybe remove this from the templates if we're not using it)

Otherwise 

/approve

**Comment by randomvariable** [comment]
whoops

/lgtm

**Pull request merged**
