### PR TITLE
move E2Es to kubernetes 1.19.1

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**: This PR moves the E2Es to test against 1.19

**Which issue(s) this PR fixes**: Fixes #

**Special notes for your reviewer**:

/assign @fabriziopandini @gab-satchi 

**Release note**:

```release-note

```

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Comment by gab-satchi** [comment]
lgtm. small nit about removing the unused variable `VSPHERE_MACHINE_TEMPLATE ` from the readme as well https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blame/master/test/e2e/README.md#L33

**Comment by fabriziopandini** [comment]
/approve
not sure I have the required grants in CAPV

**Pull request merged**
