### PR TITLE
Remove extra space in e2e image names

### PR DESCRIPTION
**Pull request by johananl**
**What this PR does / why we need it**: #1434 introduced an extra space in the e2e image names.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

None

**Special notes for your reviewer**:

None

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by johananl** [comment]
>create_test.go:67: failed to clone vm

Seems like a flake.

**Comment by johananl** [comment]
>create_test.go:67: failed to clone vm

Seems like a flake.
/retest

**Comment by srm09** [comment]
Nice catch!
/lgtm
/approve

**Pull request merged**
