### PR TITLE
[release-1.9] 🌱 hack/e2e don't add binary files to artifacts and also censor base64 encoded values

### PR DESCRIPTION
**Pull request by chrischdi**
Manual cherry-pick of #2989

Also syncs e2e.sh as good as possible to what we have on main.

### CODE REVIEW

**Comment by chrischdi** [comment]
/cherry-pick release-1.7

cherry-picks did work out locally, let's see if this works remote here too.

**Comment by sbueringer** [comment]
Interesting diff (seems like 2-3 different PRs? ;))

/lgtm
/approve

**Pull request merged**
