### PR TITLE
🌱 Update Calico in e2e tests to v3.24.0

### LINKED ISSUE #1605: calico-node pods are crashlooping in e2e tests
/kind bug

**What steps did you take and what happened:**

Run the e2e tests while skipping resource cleanup as follows:

```
SKIP_RESOURCE_CLEANUP=true GINKGO_FOCUS="\[PR-Blocking\]" make e2e
```

Get the kubeconfig of the management cluster:

```
kind get kubeconfig --name $(kind get clusters | head -n 1) > /tmp/kind-kubeconfig
```

Get the kubeconfig of the workload cluster:

```
export KUBECONFIG=/tmp/kind-kubeconfig
clusterctl get kubeconfig quick-start-gf4dbv -n quick-start-x9uf43 > /tmp/workload-kubeconfig
```

Wait for the workload cluster to converge on vSphere, then check the pod status on the workload cluster:

```
export KUBECONFIG=/tmp/workload-kubeconfig
kubectl get pods -A
```

Output:

```
NAMESPACE     NAME                                               READY   STATUS              RESTARTS        AGE
kube-system   calico-kube-controllers-56d67c99f7-6v2g8           0/1     ContainerCreating   0               54m
kube-system   calico-node-d6bqg                                  0/1     CrashLoopBackOff    15 (27s ago)    53m
kube-system   calico-node-n846s                                  0/1     CrashLoopBackOff    15 (2m7s ago)   54m
kube-system   coredns-64897985d-pfnd4                            0/1     ContainerCreating   0               55m
kube-system   coredns-64897985d-qm7gd                            0/1     ContainerCreating   0               55m
kube-system   etcd-quick-start-gf4dbv-vwc76                      1/1     Running             0               55m
kube-system   kube-apiserver-quick-start-gf4dbv-vwc76            1/1     Running             0               55m
kube-system   kube-controller-manager-quick-start-gf4dbv-vwc76   1/1     Running             0               55m
kube-system   kube-proxy-755z7                                   1/1     Running             0               55m
kube-system   kube-proxy-n5qgv                                   1/1     Running             0               53m
kube-system   kube-scheduler-quick-start-gf4dbv-vwc76            1/1     Running             0               55m
kube-system   kube-vip-quick-start-gf4dbv-vwc76                  1/1     Running             0               55m
kube-system   vsphere-cloud-controller-manager-h9zvb             1/1     Running             0               53m
kube-system   vsphere-cloud-controller-manager-rhfxm             1/1     Running             0               54m
kube-system   vsphere-csi-controller-bc4676cd9-8wp4g             0/5     ContainerCreating   0               54m
kube-system   vsphere-csi-node-2qfd2                             0/3     ContainerCreating   0               53m
kube-system   vsphere-csi-node-mlvhs                             0/3     ContainerCreating   0               54m
```

**What did you expect to happen:**
I expected the workload cluster pods to be ready.

**Anything else you would like to add:**
Note that this issue **isn't** failing the test because the test doesn't validate pod status, it only checks for a successful cluster creation.

**Environment:**

- Cluster-api-provider-vsphere version: `main` as of `9ffa6d8f6a606fe1457317b235551c7a5c74850f`.
- Kubernetes version: (use `kubectl version`): `v1.23.5`
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04 LTS`

### PR DESCRIPTION
**Pull request by johananl**
**What this PR does / why we need it**: This PR updates the Calico manifest used by the e2e tests to `v3.24.0`. It also fixes #1605.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1605

**Special notes for your reviewer**:

This is a large diff. To ensure it is up to date with upstream, run the following:

```
curl https://raw.githubusercontent.com/johananl/cluster-api-provider-vsphere/johananl/e2e-update-calico/test/e2e/data/cni/calico/calico.yaml > pr.yaml
curl https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/calico.yaml > upstream.yaml
diff upstream.yaml pr.yaml && echo "OK"
```

To test this PR, follow the reproduction instructions of #1605 and ensure the pods converge.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Update Calico to `v3.24.0` in e2e tests.
```

### CODE REVIEW

**Review by srm09 — COMMENTED** [review]
Use quay.io prefix URLs for images instead of the docker.io URLs since they are rate limited.

**Comment by johananl** [comment]
> Use quay.io prefix URLs for images instead of the docker.io URLs since they are rate limited.

Good point, thanks. I can [see](https://github.com/projectcalico/calico/issues/4833#issuecomment-1209612283) that the Calico maintainers have switch to quay.io as the official registry lately. Looks like they're going to update the manifests soon, too, so hopefully next time we shouldn't have to manually patch the official manifests.

For the record, here is what I used to switch to Quay in this PR:

```
sed -i 's/image: docker.io/image: quay.io/g' test/e2e/data/cni/calico/calico.yaml
```

**Comment by johananl** [comment]
The registry has been updated to quay.io @srm09.

**Comment by johananl** [comment]
Broken CI is fixed in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1608.

**Comment by srm09** [comment]
/retitle 🌱 Update Calico in e2e tests to v3.24.0

**Comment by randomvariable** [comment]
looks like the test failure is unrelated?
/override pull-cluster-api-provider-vsphere-test

**Comment by johananl** [comment]
> looks like the test failure is unrelated? /override pull-cluster-api-provider-vsphere-test
> 
> probably don't have permissions to do that.

The broken CI is indeed unrelated to this change (see my comment above). We are waiting for #1602 to get merged.

**Pull request merged**
