### PR TITLE
🐛 apis: fix missing categories marker for VShpereVM in v1alpha3 and v1alpha4

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Adds the missing `categories=cluster-api` marker to:
* `apis/v1alpha3/vspherevm_types.go`
* `apis/v1alpha4/vspherevm_types.go`

The missing markers result into inconsistent results for the generated CRD's.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Related to #1928

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by chrischdi** [comment]
Note: on main this is reproducible using the following script:

```
function test:generate() {
  rm -rf tmp tmp2
  mkdir -p tmp tmp2
  eval $CONTROLLER_GEN ${1}
  for i in {1..100}; do
    printf "> %02d\n" "$i";
    eval $CONTROLLER_GEN ${1}2
    diff tmp${2} tmp2${2} || break
  done
}

CONTROLLER_GEN="$(pwd)/hack/tools/bin/controller-gen"
GENARGS="paths=./apis/v1alpha3 \
    paths=./apis/v1alpha4 \
    paths=./apis/v1beta1 \
    crd:crdVersions=v1 \
    output:crd:dir=tmp"

test:generate ${GENARGS} "/infrastructure.cluster.x-k8s.io_vspherevms.yaml"
```

Example failure:
```
❯ test:generate ${GENARGS} "/infrastructure.cluster.x-k8s.io_vspherevms.yaml"
> 01
> 02
> 03
11,12d10
<     categories:
<     - cluster-api
```

> **Note:** this script may still exit on the cases where `x-kubernetes-map-type: atomic` is added/removed or `- apiGroup` is added or removed from `required`.

**Comment by sbueringer** [comment]
Should be fine to fix it this way, given that there is only one categories field per CRD.

Would be good to have a controller-tools issue for it though (just to report it)

/lgtm

**Comment by sbueringer** [comment]
I would cherry-pick this to all supported branches

/cherry-pick release-1.7

**Pull request merged**
