### PR TITLE
🌱 Clean up stale nodes left behind on a workload cluster

### LINKED ISSUE #1519: Stale nodes left behind on a workload cluster
/kind bug

**What steps did you take and what happened:**
- Create a workload cluster with a MHC targeting NotReady worker nodes 
- For some reason, the worker nodes of the cluster do not get into the Ready state (the CPI pods do not get deployed)
- MHC reaps the not Ready Machines to retry creating new nodes.
```bash
[vc-robo@sc2-10-187-103-200 worker]$ k get nodes
NAME STATUS ROLES AGE VERSION
robo-antrea-control-plane-2z4j9 Ready control-plane,master 8h v1.20.4
robo-antrea-control-plane-gpwnq Ready control-plane,master 8h v1.20.4
robo-antrea-control-plane-j8kq5 Ready control-plane,master 16h v1.20.4
robo-antrea-md-0-6769cbc7cd-25h2m NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-25xg9 NotReady <none> 14h v1.20.4
robo-antrea-md-0-6769cbc7cd-445kj NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-49cxp NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-4cc59 Ready <none> 8h v1.20.4
robo-antrea-md-0-6769cbc7cd-4n6wj NotReady <none> 9h v1.20.4
robo-antrea-md-0-6769cbc7cd-4p5c4 NotReady <none> 11h v1.20.4
robo-antrea-md-0-6769cbc7cd-4t2hd NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-52gwb NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-54vmq NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-5mj54 NotReady <none> 14h v1.20.4
robo-antrea-md-0-6769cbc7cd-5xw9j NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-6vh4z NotReady <none> 9h v1.20.4
robo-antrea-md-0-6769cbc7cd-6zvrd NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-7czsf NotReady <none> 12h v1.20.4
robo-antrea-md-0-6769cbc7cd-7l6xp NotReady <none> 8h v1.20.4
``` 

**What did you expect to happen:**
Reaped nodes by MHC should not show up in the output of `kubectl get nodes`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: v1.1.x
- Kubernetes version: (use `kubectl version`): v.1.20.4
- OS (e.g. from `/etc/os-release`): photonOS

### PR DESCRIPTION
**Pull request by scdubey**
**What this PR does / why we need it**:
Reaped nodes by MHC show up in the output of `kubectl get nodes` 

The name of the k8s node is same to the name of the owning CAPI Machine. We implemented a workaround that post the deletion of the VSphereMachine, we get the workload cluster k8s client and attempt to delete the node.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1519 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by srm09** [comment]
This logic should be a part of the VSphereVM controller's `ReconcileDelete` logic.

**Comment by srm09** [comment]
/retitle 🌱 Clean up stale nodes left behind on a workload cluster

**Comment by aartij17** [comment]
Closing this PR in favor of #1551 
/close

**Pull request closed without merging**
