### PR TITLE
[WIP] Testing Reconcile for vimmachine

### LINKED ISSUE #1469: Add unit tests for vim machine reconciliation
/area testing

Add tests for below scenarios in vimmachine.go:

1. Successfully reconcile vim machine with following checks:
- Check if VSphereMachine status is Ready.
- Check if VsphereMachine status contains network details like mac address, ip addresses, whether connection established or not etc.
- Check if VSphereMachine spec contains provider ID
- Check if VMProvisionedCondition is set.
2. Should ignore reconciliation in below cases:
- if the ownerReferences is set in VsphereVM spec.
- if cluster and machine labels are set in VsphereVM spec.
- if bootstrap ref is set in VsphereVM spec.
- if vsphere machine's VM clone spec is set in VsphereVM spec.
- if failure domains(if present) are set in VsphereVM spec.
3. Reconcile failure scenarios:
- Failure in reconciling network, check if status and conditions corresponds to failed state.
- Failure in reconciling provider ID
(Can be thought of more error scenarios if time persists)
4. Successfully reconcile vim machine deletion:
- Check if VMProvisionedCondition is set to false.
- Check if vim machine is actually deleted by fetching the vim machine object.

### PR DESCRIPTION
**Pull request by DiptoChakrabarty**
**What this PR does / why we need it**:
This performs tests for reconcile for  vimmachine under `pkg/services/vimmachine`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1469 #1478

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by DiptoChakrabarty** [comment]
hey @geetikabatra  @Ankitasw can you once check if I am moving in the right direction for this , just added the case for point 1 in issue #1469 . Thank You

**Comment by DiptoChakrabarty** [comment]
Hi I am getting two errors locally with the above changes , can you just point me in the right direction for this
Selection_001

Selection_002

the pointer  error is due to vimMachineService.ReconcileNormal(machineCtx) I believe , is there some way to mitigate that.

**Comment by srm09** [comment]
@geetikabatra Can you help the original author out?

**Comment by geetikabatra** [comment]
Sure @srm09

**Comment by srm09** [comment]
@geetikabatra Has this moved along ahead, if not, let's close loop with the original author and close this one? It has been in this blocked state for a while now.

**Comment by srm09** [comment]
/close
Due to inactivity

**Pull request closed without merging**
