### PR TITLE
clusterctl: VM folder should be optional

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

/assign @akutz

### CODE REVIEW

**Comment by figo** [comment]
good catch, although vm folder is required for VMC env

/lgtm

**Comment by akutz** [comment]
> good catch, although vm folder is required for VMC env
> 
> /lgtm

Technically it's required for any env where you can't deploy at the root. But for envs sans folders, this blocks them. We basically have an inflexible generator at the moment that we need to improve to tolerate different environment configs.

**Comment by andrewsykim** [comment]
/hold

Should we log warning if it's not set?

**Comment by akutz** [comment]
Hi @andrewsykim,

I recommend the following:

```shell
[ ! "${VM_FOLDER+x}" ] || VM_FOLDER="${VM_FOLDER:?empty}"
echo "VM_FOLDER=${VM_FOLDER}"
```

The above script says either `VM_FOLDER` must be not set, or, if set, must not be the empty value. Otherwise an error is printed. For example:

**`VM_FOLDER` is defined, but empty**

```shell
$ cat <<EOF | VM_FOLDER= bash -s --
[ ! "\${VM_FOLDER+x}" ] || VM_FOLDER="\${VM_FOLDER:?empty}"
echo "\${VM_FOLDER}"
EOF
bash: line 1: VM_FOLDER: empty
```

**`VM_FOLDER` is not defined**

```shell
$ cat <<EOF | bash -s --
[ ! "\${VM_FOLDER+x}" ] || VM_FOLDER="\${VM_FOLDER:?empty}"
echo "\${VM_FOLDER}"
EOF

```

**`VM_FOLDER` is defined and not empty**

```shell
$ cat <<EOF | VM_FOLDER="workloads" bash -s --
[ ! "\${VM_FOLDER+x}" ] || VM_FOLDER="\${VM_FOLDER:?empty}"
echo "\${VM_FOLDER}"
EOF
workloads
```

/hold

**Comment by andrewsykim** [comment]
In this case we don't want to log if VM_FOLDER is set so it might be an easier check than that 🤔

**Comment by andrewsykim** [comment]
@akutz updated, let me know what you think

**Pull request merged**
