### PR TITLE
remove deploying workers to speed CI

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**: This PR removes deploying workers to speed up CI. it works locally but takes too much time on prow

**Which issue(s) this PR fixes** : Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by vincepri** [comment]
what about increasing the requested CPU on prow instead?

**Comment by yastij** [comment]
This unblocks CI signal until the test machinery is fixed

/assign @ncdc

**Comment by yastij** [comment]
@vincepri - I'm not sure If it's CPU related see [here](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-vsphere/cluster-api-provider-vsphere-presubmits.yaml#L243)

I think it's mostly connectivity issues, but I don't have enough bandwidth to explore it. Running outside of Prow seems to be working.

**Comment by vincepri** [comment]
Sounds good!

/lgtm

**Comment by ncdc** [comment]
What's the plan for restoring testing w/workers?

**Comment by yastij** [comment]
@ncdc - I’m planning on adding periodic e2e prow job with longer timeouts

**Comment by ncdc** [comment]
SGTM, thanks!
/approve

**Pull request merged**
