### PR TITLE
Bump cluster-api to v0.3.14

### PR DESCRIPTION
**Pull request by MarcelMue**
**What this PR does / why we need it**:

It's a precursor to updating dependencies for CAPI v1alpha4

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MarcelMue** [comment]
Sorry for the noise - I fumbled my rebase while multi-tasking :D

**Review by yastij — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
