### PR TITLE
🌱 test/e2e: add check at anti-affinity test to ensure enough hosts exist

### LINKED ISSUE #1975: CI: e2e anti-affinity tests are red
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

The prowjob [periodic-e2e-main](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-e2e-main), the test for `Cluster creation with anti affined nodes should create a cluster with anti-affined nodes` is red for already a long time.
And same for the presubmit [pr-full-e2e](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#pr-full-e2e).

The issue is that there are not the required numbers of hypervisors available. To be more concrete:
The test assumes to have five hosts / hypvervisors:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/b43e70e6ce7cdd29a923bc83d408588b225b3023/test/e2e/anti_affinity_test.go#L62

But that is not the case. I tested this via https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1974 which adds a  check to verify there are equal or more hosts available compared to the worker count.

```
  [FAILED] This test requires more or equal number of hosts compared to the WorkerNodeCount. Expected at least 5 but only got 4 hosts.
  Expected
      <bool>: false
```
[source](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/1974/pull-cluster-api-provider-vsphere-full-e2e/1677282952632864768)

PR for the additional check: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1974

**What did you expect to happen:**

The test to succeed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I currently see two options:
* Lower the workerNodeCount to 4 for this job or maybe even just use the number of hosts.
* Having a look at the test infrastructure (if there is somebody having access)

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Adds a check to the currently broken anti-affinity test to ensure enough hosts are available for the given anti-affinity test input.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1975

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

/test help

### CODE REVIEW

**Comment by sbueringer** [comment]
Sounds like a good improvement to make the test failure easier to triage

/lgtm

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-full-e2e

Uh oh, `>` != `>=` :D

**Pull request merged**
