### PR TITLE
🌱 flavorgen: Bump CSI to v3.3.0

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Bumps vsphere CSI to v3.3.0

* CSI now works with SHA256 thumbprints

xref: #2519

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Comment by sbueringer** [comment]
@chrischdi The other PR is merged, I guess we can merge once the tests are green (aka already remove the hold?)

**Comment by chrischdi** [comment]
Let's see if this gets green.

**Comment by chrischdi** [comment]
/hold

To merge #3024 first

**Comment by sbueringer** [comment]
Otherwise lgtm so far

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

/test pull-cluster-api-provider-vsphere-e2e-govmomi-conformance-ci-latest-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-conformance-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-upgrade-1-30-1-31-main
/test pull-cluster-api-provider-vsphere-e2e-supervisor-conformance-ci-latest-main
/test pull-cluster-api-provider-vsphere-e2e-supervisor-conformance-main
/test pull-cluster-api-provider-vsphere-e2e-supervisor-main
/test pull-cluster-api-provider-vsphere-e2e-supervisor-upgrade-1-30-1-31-main
/test pull-cluster-api-provider-vsphere-e2e-vcsim-govmomi-main
/test pull-cluster-api-provider-vsphere-e2e-vcsim-supervisor-main

**Pull request merged**
