### PR TITLE
Bump gcr.io/cloud-provider-vsphere/cpi/release/manager from v1.0.0 to v1.1.0.

### PR DESCRIPTION
**Pull request by farodin91**
Signed-off-by: jan.jansen <jan.jansen@gdata.de>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by farodin91** [comment]
@ncdc I'm not sure why this fails after my change.

**Comment by ncdc** [comment]
@farodin91 it's not your change - we have other e2e issues. Thanks for your patience as we work through them!

**Comment by yastij** [comment]
/lgtm
/approve

this will merge after #971 merges

**Pull request merged**
