### PR TITLE
🌱  [release-1.7] Bump to Go 1.20.8

### PR DESCRIPTION
**Pull request by Ankitasw**
What this PR does / why we need it:
Bumps Go version to 1.20.8

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/test pull-cluster-api-provider-vsphere-e2e-full-release-1-7 

Thank you!

**Comment by chrischdi** [comment]
Related to #2020 and https://github.com/vmware/govmomi/pull/3175

**Pull request merged**
