### PR TITLE
:seedling: OWNERS: Refresh of owners as per meeting of 2023/06/22

### PR DESCRIPTION
**Pull request by randomvariable**
**What this PR does / why we need it**:

Refresh of OWNERS to reflect current folk as per the meeting of 2023/06/22

Related PRs:
* https://github.com/kubernetes/test-infra/pull/30190
* https://github.com/kubernetes/org/pull/4345
* https://github.com/kubernetes/k8s.io/pull/5621

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by randomvariable** [comment]
/hold 
for lazy consensus until 2023/08/01

**Comment by srm09** [comment]
/approve
Great to see folks stepping in, and hoping this moves the project at a warp speed.

**Pull request merged**
