### PR TITLE
📖 docs: document tagging the test go module

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

We added a go module in `test` since v1.9. We also should add tags for the test module.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
I don't mind but just wanted to say that we don't have a book in CAPV and we also probably don't want to keep the release tasks doc up-to-date on all active release branches

**Comment by chrischdi** [comment]
I wanted to bubble up the release tasks, because the test tag was already forgotten for the last release (v1.9.2).

**Comment by sbueringer** [comment]
Yup good point. But don't we have the problem for all release branches. And also in general if we rely on release-tasks.md being up-to-date on all branches?

**Comment by chrischdi** [comment]
> Yup good point. But don't we have the problem for all release branches. And also in general if we rely on release-tasks.md being up-to-date on all branches?
> 
> (but definitely fine, this also might be a special case)

Ack, this special case was just the release-1.9 branch did lack this information forever, and I usually copy the tag + push commands from the branch so I don't miss the test tag / leave it out :-)

**Comment by sbueringer** [comment]
All good! If you tend to do the same for other branches, let's cherry-pick this further :)

**Comment by chrischdi** [comment]
No need to, the module was introduced in v1.9 :-)

**Pull request merged**
