### PR TITLE
Reconcile storage policy after cloning the VM

### LINKED ISSUE #1146: Storage policy applied before cloning causes clone to fail across datastores
/kind bug

**What steps did you take and what happened:**
Use a template that doesn't have a storage policy to spin up worker nodes on a different datastore with a storage policy.  The current code sets the new storage policy before cloning, and we receive the following logs in our vCenter logs:
`Changing or applying VM Storage Policies with Data Service capabilities during clone operations is disallowed. VM Storage Policies with Data Service capabilities can be assigned to the provisioned VM after the clone operation has been completed and before the VM has been powered on.`  Even though [this article](https://kb.vmware.com/s/article/78488) states that this occurs when the datastores have different settings, we verified that this occurs even when the datastores have all the same configuration settings (the only differences between our datastores are name and size) and the storage policy is compliant with both the source and destination datastore.  We also verified that this still happens when the template lives on the same datastore that the worker node would live on, which removes datastore differences from the equation.

**What did you expect to happen:**
I expected the template to be cloned to the new datastore with the storage policy applied.  One solution here, which is currently used by the terraform vsphere provider, is to clone the template without a storage policy and then switch to the new policy.  This does make the clone take longer, but solves this problem.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: v0.7.6
- Kubernetes version: (use `kubectl version`): v1.18.12
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 machines
- vCenter: 6.7

### PR DESCRIPTION
**Pull request by gab-satchi**
**What this PR does / why we need it**:
This PR fixes an issue where host based storage policies couldn't be applied to VMs during the clone process. With these changes, the storage policy is reconciled separately after the clone VM, reconcile network and reconcile metadata completes. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1146 

**Special notes for your reviewer**:
The reconcile function returns early if the VM is powered on. This is to avoid the scenario where the storage policies have already been reconciled and the VM is in a running state but the user either attaches extra disks or uses CSI to provision new disks with a different storage policy. The capv controller should not overwrite the storage policy on any disks other than the first 'root' one. 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by srm09 — COMMENTED** [review]
minor nits, other lgtm

**Review by yastij — COMMENTED** [review]
/approve

@gab-satchi - this passed the storage policy test. this looks overall good

**Pull request merged**
