### PR TITLE
🐛 CAPV CSI driver isn't passing TLS thumbprint

### LINKED ISSUE #1162: CAPV CSI driver isn't passing TLS thumbprint
/kind bug

**What steps did you take and what happened:**
I have a largely stock configuration and the `vsphere-csi-controller` is in CrashLoopBackOff. Reviewing the logs I am seeing this:

```
{"level":"error","time":"2021-03-29T20:53:48.890658758Z","caller":"service/service.go:135","msg":"failed to init controller. Error: Post https://e4vmw0vic06.datalinklabs.local:443/sdk: x509: certificate signed by unknown authority","TraceId":"bb6ce13f-5059-40aa-948d-abe39ee9ceeb","stacktrace":"sigs.k8s.io/vsphere-csi-driver/pkg/csi/service.(*service).BeforeServe\n\t/build/pkg/csi/service/service.go:135\ngithub.com/rexray/gocsi.(*StoragePlugin).Serve.func1\n\t/go/pkg/mod/github.com/rexray/gocsi@v1.2.1/gocsi.go:246\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:66\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:57\ngithub.com/rexray/gocsi.(*StoragePlugin).Serve\n\t/go/pkg/mod/github.com/rexray/gocsi@v1.2.1/gocsi.go:211\ngithub.com/rexray/gocsi.Run\n\t/go/pkg/mod/github.com/rexray/gocsi@v1.2.1/gocsi.go:130\nmain.main\n\t/build/cmd/vsphere-csi/main.go:64\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"info","time":"2021-03-29T20:53:48.890709507Z","caller":"service/service.go:110","msg":"configured: \"csi.vsphere.vmware.com\" with clusterFlavor: \"VANILLA\" and mode: \"controller\"","TraceId":"bb6ce13f-5059-40aa-948d-abe39ee9ceeb"}
time="2021-03-29T20:53:48Z" level=info msg="removed sock file" path=/var/lib/csi/sockets/pluginproxy/csi.sock
time="2021-03-29T20:53:48Z" level=fatal msg="grpc failed" error="Post https://e4vmw0vic06.datalinklabs.local:443/sdk: x509: certificate signed by unknown authority"
```

I am providing the TLS fingerprint via the `clusterctl` configuration. I did notice the `secret/csi-vsphere-config` object doesn't include the fingerprint key/value pair.

**What did you expect to happen:**
I'd expect it to either use the TLS fingerprint or give me an option to accept insecure certificates.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by PatrickLaabs**
**What this PR does / why we need it**:
With this PR I changed a few lines of code.

packaging/flavorgen/flavors/crs/csi.go:
	config.Global.Thumbprint = env.VSphereThumbprint
	config.Global.Insecure = env.VSphereInsecure

packaging/flavorgen/flavors/env/envsubts_consts.go
	VSphereInsecure              = true

With this, I was able to create a new 'cluster-template.yaml' inside .cluster-api/overrides... where the Global-Section of the csi-vsphere-config Secret gets the thumbprint and insecure flag passed.

` stringData:
     csi-vsphere.conf: |+
        [Global]
        insecure-flag = true
        thumbprint = "${VSPHERE_TLS_THUMBPRINT}"
        cluster-id = "${NAMESPACE}/${CLUSTER_NAME}"`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1162

**Special notes for your reviewer**:
Since the Insecure-Flag is defined as a bool inside packaging/flavorgen/flavors/crs/types/cloudprovider_types.go
at line 88, I was not able to make this Insecure-Flag configurable via the clusterctl.yaml under ~/.clusterctl-api.

Changing it to a string, would make it configurable.
Like so: `Insecure string `gcfg:"insecure-flag,omitempty" json:"insecure,omitempty"`` but comes with the side-effect, that the file packaging/flavorgen/flavors/crs/types/cloudprovider_encoding_test.go throws me an error `cannot use true (untyped bool constant) as string...`
Since changing the type of the Insecure-Flag causes some impact on the testing file (And I am not sure, which side-effects this could lead to) I did not changed the typed and let it remain as a bool.
Maybe a maintainer could have a look at this and maybe help me out with this 😄 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Passing Thumbprint and Insecure-Flag (set as true in default) to the generated Cluster-Manifests file)
```

### CODE REVIEW

**Comment by srm09** [comment]
/retitle 🐛 CAPV CSI driver isn't passing TLS thumbprint
/ok-to-test

**Comment by PatrickLaabs** [comment]
Hi everyone,
I am a little bit confused with the Makefile..

Running it locally with `make generate` works, but changes some files... Sometimes four files a changed (shown below), sometimes only one (https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1812/files#diff-7ddd4fa1ed03041b5af36e2959605ee9861e6d3ea2c1b6f3c8f97facd66676ab)

Can you help me with this? 😢 

---

diff --git a/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml b/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
index e5d05e22..20b9b77a 100644
--- a/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
+++ b/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
@@ -322,7 +322,6 @@ spec:
                     description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                     type: string
                 type: object
-                x-kubernetes-map-type: atomic
               server:
                 description: Server is the address of the vSphere endpoint.
                 type: string
diff --git a/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml b/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
index bbfff217..7609ef5a 100644
--- a/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
+++ b/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
@@ -944,10 +944,10 @@ spec:
                                 description: Name is the name of resource being referenced
                                 type: string
                             required:
-                            - apiGroup
                             - kind
                             - name
                             type: object
+                            x-kubernetes-map-type: atomic
                           type: array
                         deviceName:
                           description: DeviceName may be used to explicitly assign
diff --git a/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml b/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
index 697563c5..fc4d233d 100644
--- a/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
+++ b/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
@@ -833,10 +833,10 @@ spec:
                                           being referenced
                                         type: string
                                     required:
-                                    - apiGroup
                                     - kind
                                     - name
                                     type: object
+                                    x-kubernetes-map-type: atomic
                                   type: array
                                 deviceName:
                                   description: DeviceName may be used to explicitly
diff --git a/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml b/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
index 6324b355..fcf324ad 100644
--- a/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
+++ b/config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
@@ -81,7 +81,6 @@ spec:
                     description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                     type: string
                 type: object
-                x-kubernetes-map-type: atomic
               cloneMode:
                 description: CloneMode specifies the type of clone operation. The
                   LinkedClone mode is only support for templates that have at least
@@ -910,6 +909,7 @@ spec:
                     description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                     type: string
                 type: object
+                x-kubernetes-map-type: atomic
               cloneMode:
                 description: CloneMode specifies the type of clone operation. The
                   LinkedClone mode is only support for templates that have at least
@@ -991,10 +991,10 @@ spec:
                                 description: Name is the name of resource being referenced
                                 type: string
                             required:
-                            - apiGroup
                             - kind
                             - name
                             type: object
+                            x-kubernetes-map-type: atomic
                           type: array
                         deviceName:
                           description: DeviceName may be used to explicitly assign

**Comment by PatrickLaabs** [comment]
I did a rebase on my branch and used the latest changes made to the main branch. Especially the #1800 fix.
Seems to work now. Maybe this is good to know for the #1757 issue.

How can i fix the CLA stuff?
I forgot to configure my git client correctly, but now - as seen in the latest commits - it is. @srm09 Can you help me with the CLA "issue"? 😄

**Comment by PatrickLaabs** [comment]
Well, my CLA is not being accepted, even after editing the commits with my correct creds.
I will close this PR and create a new one,  based upon the latest code changes on main.

/close

**Pull request closed without merging**
