### PR TITLE
🌱 Bump CPI to v1.30.0-alpha

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Looks like gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.30.0-alpha is not available yet

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

pending CI

**Pull request merged**
