### PR TITLE
🌱 Add kubetest files for upstream e2e tests

### PR DESCRIPTION
**Pull request by chrischdi**
Adds kubetest yaml files for #2452

### CODE REVIEW

**Comment by chrischdi** [comment]
One observation: ubuntu package `nfs-common` is missing for some tests to succeed.

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

One Q: Do we have a reference for these configs - are they cloned from somewhere else?

**Comment by chrischdi** [comment]
> /lgtm
> 
> One Q: Do we have a reference for these configs - are they cloned from somewhere else?

added a reference link.

**Review by killianmuldoon — COMMENTED** [review]
Thanks for refs!

/lgtm
/approve

/hold
(not sure when you want to merge)

**Comment by chrischdi** [comment]
Thanks for the hold. Currently running it in a test environment, and I will then compare the properties in the junit tests with the upstream tests, to ensure we use the very same configuration.

**Comment by chrischdi** [comment]
/hold cancel

one more thing

**Comment by chrischdi** [comment]
ah damn :D wanted to hold again.

**Pull request merged**
