### PR TITLE
🌱 Minor fixups vsphere.yaml's

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Tests on the mirror: https://github.com/team-cluster-api/cluster-api-provider-vsphere/pull/53

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold 
for tests on mirror

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
/hold cancel

tests on mirror are green

**Pull request merged**
