### PR TITLE
🌱 test: Bump autoscaler to v1.31.0

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

/test help

/cherry-pick release-1.11

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Thank you

/lgtm
/approve

**Comment by fabriziopandini** [comment]
/lgtm
/approve

Nice!

**Pull request merged**
