### PR TITLE
🐛 Fix datastore selection based on StoragePolicy

### PR DESCRIPTION
**Pull request by zhanggbj**
**What this PR does / why we need it**:

When storage policy is specified, CAPV will fetch compatible datastores and randomly selects one, however the return set also contains datastore cluster. This will leads to long-time retries and even clone failures. Fix it by adding a filter when to get compatible datastores.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

#1914
#1853 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Fix datastore selection based on StoragePolicy

```

### CODE REVIEW

**Review by yastij — COMMENTED** [review]
/approve

**Comment by zhanggbj** [comment]
@yastij  all tests passed and ready for a review. Thanks!
Also opened #1962 to tracking UT effort.

**Comment by zhanggbj** [comment]
This change is tested locally, and it works well.
It's eady for another review @yastij @vrabbi @srm09, thx!

**Comment by sbueringer** [comment]
@zhanggbj Should this be backported into v1.7/v1.6/v1.5?

**Comment by zhanggbj** [comment]
@sbueringer Good point! I think yes, just checked code base and this bug already existed since v1.5, so we should backport it.

**Comment by sbueringer** [comment]
Thx for checking!

/cherry-pick release-1.7

**Pull request merged**
