### PR TITLE
Update README with new OVA links

### LINKED ISSUE #1511: Published OVAs are obsolete
/kind bug

(this is also a security bug, and also an enhancement request 😀 )

**What steps did you take and what happened:**

Go to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/README.md#kubernetes-versions-with-published-ovas. Currently shows:

> Kubernetes | CentOS 7 | Ubuntu 18.04 | Photon 3
> -- | -- | -- | --
> v1.17.16 | ova, sha256 | ova, sha256 | ova, sha256
> v1.18.14 | ova, sha256 | ova, sha256 | ova, sha256
> v1.19.6 | ova, sha256 | ova, sha256 | ova, sha256
> v1.20.1 | ova, sha256 | ova, sha256 | ova, sha256

Those versions are outdated and have security flaws.

**What did you expect to happen:**

Images to be updated when new k8s are released.

**Anything else you would like to add:**

There are more up to date OVAs from tanzu-community-edition: [Tanzu Community Edition 0.11.0 product page](https://customerconnect.vmware.com/downloads/get-download?downloadGroup=TCE-0110). NB: those require a VMware account.

### PR DESCRIPTION
**Pull request by codenrhoden**
**What this PR does / why we need it**:
Updates README to point to updated OVA's for CentOS 7, Ubuntu 18.04, Ubuntu 20.04, and Photon 3. This is the first time links to Ubuntu 20.04 images have been published

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1511

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by srm09** [comment]
Hey @codenrhoden thanks for taking the time to create the newer set of images. I was hoping if there is a way for us to push newer images on a regular cadence via an automated pipeline?
I would love to hear your thoughts on this one. This effort might also help us to run the e2e testing suite against the latest k8s version.

**Comment by codenrhoden** [comment]
@srm09 Yeah, that's why I pinged @kkeshavamurthy on #1511. It's definitely something you two should talk about. :)

I think the pieces are in place if you wanted it be driven by Prow. I know CAPG does something similar -- it runs a nightly job to update the CAPG images if needed, and they run their CI against those new images daily (I think).

**Comment by MaxRink** [comment]
/lgtm 
from my side
regarding CI, we have tome more advanced test cases we use for images (like not only bootstrapping but also trying out things like CSI  (which depend on host packages) and we would be open in contributing that work upstream :)

**Comment by srm09** [comment]
@MaxRink Can you create an issue for that part and we could start a discussion there? 
@codenrhoden Thanks for publishing the updated images. I will talk to @kkeshavamurthy more for that part.

**Pull request merged**
