### PR TITLE
Update KIND references to v0.4.0

### PR DESCRIPTION
**Pull request by codenrhoden**
**What this PR does / why we need it**:
Use KIND v0.4.0 in e2e tests, and update docs to have users download the
latest version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by codenrhoden** [comment]
I'm glad the CRD test is holding this up. The E2E actually failed when I looked at the logs, but reported success. 😞   More work to do here...

**Comment by akutz** [comment]
Hi @codenrhoden,

Should this PR still be on hold?

**Comment by codenrhoden** [comment]
> Should this PR still be on hold?

Yes, it requires a bit more work that I haven't done yet. =)

**Comment by codenrhoden** [comment]
I bumped the `kubeadm` API version to `v1beta2`, which is needed because KIND v0.4.0 now uses K8s 1.15.0 as a default, and that moved things along...  But there seems to be a SAN issue for the certs, as the log as showing:
`Unable to connect to the server: x509: certificate is valid for 10.96.0.1, 172.17.0.2, 172.17.0.2, 192.168.2.17, not 0.0.0.0`.

**Comment by codenrhoden** [comment]
Okay, I finally found the issue. Needed to set the APIServer IP to be the IP of the VM, and previously it was just set to `0.0.0.0`, and the Cert wasn't happy about that.

/hold cancel

**Comment by codenrhoden** [comment]
@akutz I believe this is ready for a `/approve`, unless @figo sees anything wrong with the API server address change.

**Comment by akutz** [comment]
Hi @codenrhoden,

I'm curious about whatever issues were holding this up in case the solutions would be helpful for people wanting to use Kind 0.4.0 locally.

**Comment by codenrhoden** [comment]
@akutz The hold up was getting passed the error mentioned in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/388#issuecomment-509332574. Specifically the cert issue, which was fixed with https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/388/files#diff-9c7973055f5ff7fb69078ea7a53f5172R5.

Why this was only a problem now? I'm not sure, as I didn't dig too deep into it. I would guess it's because KIND 0.4.0 defaults a v1.15.0 cluster, and perhaps something changed there. **Or** it's because of a different behavior with kubeadm. I'm really not sure.

**Comment by codenrhoden** [comment]
As an aside, it was nice to see the e2e test failing when I came back to this. As it was previously passing (erroneously).

**Pull request merged**
