### PR TITLE
[release-1.9] 🐛 Restore v1alpha3/v1alpha4 conversion to fix SSA issue

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Manual cherry-pick of #2739

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Saw a similar issue in core CAPI e2e tests somehow

> https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2740/pull-cluster-api-provider-vsphere-e2e-release-1-9/1757853890109247488/artifacts/clusters/clusterctl-upgrade-09dram/resources/capi-kubeadm-control-plane-system/Pod/capi-kubeadm-control-plane-controller-manager-786948c544-2p4nw.yaml

> message: Back-off pulling image "registry.k8s.io/cluster-api/kubeadm-control-plane-controller:v1.5.4"

Maybe we're hitting some quota / or some other registry issue

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

/hold to let you control

**Comment by sbueringer** [comment]
/test pull-cluster-api-provider-vsphere-verify-release-1-9

(just checking if I have to rebase after the Go bump)

**Pull request merged**
