### PR TITLE
Remove vestigial NTP & Trusted CA fields

### PR DESCRIPTION
**Pull request by akutz**
/kind feature

**What this PR does / why we need it**:
This patch removes the vestigial fields for defining NTP hosts and trusted CAs as part of a `VSphereMachine`. Specifying this data now occurs via a bootstrap configuration resource ([example](https://github.com/kubernetes-sigs/cluster-api/blob/31f119ce49479505c6bf9201316e4f9ef6a0361d/bootstrap/kubeadm/api/v1alpha2/kubeadmbootstrapconfig_types.go#L33-L63)).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sidharthsurana** [comment]
@akutz naive question, I see that NTP setting is there as part of the `KubeadmConfigSpec` but I am not sure how the trusted CA Certs would be handled.  Is it going to be handled via the `Files` attribute?

**Comment by akutz** [comment]
Hi @sidharthsurana,

Exactly. I’m going to file an RFE so the bootstrap config has explicit support for additional trusted certs, but for now the additional files is the only method.

**Comment by figo** [comment]
> Hi @sidharthsurana,
> Exactly. I’m going to file an RFE so the bootstrap config has explicit support for additional trusted > certs, but for now the additional files is the only method.

Please link the PR here once you filed, thanks

/lgtm

**Comment by akutz** [comment]
> > Hi @sidharthsurana,
> > Exactly. I’m going to file an RFE so the bootstrap config has explicit support for additional trusted > certs, but for now the additional files is the only method.
> 
> Please link the PR here once you filed, thanks
> 
> /lgtm

Hi @figo,

Here you go - https://github.com/kubernetes-sigs/cluster-api/issues/1793.

**Pull request merged**
