### PR TITLE
✨ Bump CAPI to v1.8.0-beta.0

### LINKED ISSUE #3106: CAPI v1.8.0-beta.0 has been released and is ready for testing
CAPI v1.8.0-beta.0 has been released and is ready for testing.
Looking forward to your feedback before v1.8.0 release!

## For quick reference

- [CAPI v1.8.0-beta.0 release notes](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.8.0-beta.0)
- [Shortcut to CAPI git issues](https://github.com/kubernetes-sigs/cluster-api/issues)

## Following are the planned dates for the upcoming releases

CAPI v1.8.0 will be released on **Monday, 12th August 2024**.

More details of the upcoming schedule can be seen at [CAPI v1.8.0 release timeline](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/releases/release-1.8.md#timeline).

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3106

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

Pending tests

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-test-main

Flake?

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-e2e-vcsim-supervisor-main

Flake

```
Failed to get EnvVar default/owner-reference
  Expected
      <bool>: false
  to be true
  In [BeforeEach] at: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/test/e2e/e2e_setup_test.go:145 @ 07/17/24 07:11:28.464
```

**Comment by chrischdi** [comment]
Again:
```
sigs.k8s.io/cluster-api-provider-vsphere/controllers: TestReconcileNormal_WaitingForIPAddrAllocation/Deleting_a_VM_with_IPAddressClaims
sigs.k8s.io/cluster-api-provider-vsphere/controllers: TestReconcileNormal_WaitingForIPAddrAllocation
```

but I can't reproduce it locally. Also a different flake :-(

/test pull-cluster-api-provider-vsphere-test-main

**Comment by sbueringer** [comment]
Saw this one a few times now, are you using the right envtest to reproduce? (If this test is using envtest)

**Comment by chrischdi** [comment]
> Saw this one a few times now, are you using the right envtest to reproduce? (If this test is using envtest)

I can reproduce it in my cli, let's not yet in the IDE, let's see :-)

**Comment by chrischdi** [comment]
Unit test failure was due to:

- https://github.com/kubernetes-sigs/cluster-api/pull/10787

The unit test expected to get a failure on the reconciliation due to deleting.

/test pull-cluster-api-provider-vsphere-e2e-govmomi-conformance-ci-latest-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-conformance-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-upgrade-1-30-1-31-main
/test pull-cluster-api-provider-vsphere-e2e-supervisor-conformance-ci-latest-main
/test pull-cluster-api-provider-vsphere-e2e-supervisor-conformance-main
/test pull-cluster-api-provider-vsphere-e2e-supervisor-main
/test pull-cluster-api-provider-vsphere-e2e-supervisor-upgrade-1-30-1-31-main
/test pull-cluster-api-provider-vsphere-e2e-vcsim-govmomi-main
/test pull-cluster-api-provider-vsphere-e2e-vcsim-supervisor-main

**Pull request merged**
