### PR TITLE
clean up cluster-template and docs update

### LINKED ISSUE #1245: 🐛 Add `storagePolicyName` field to the `/templates/cluster-template.yaml` file
/kind bug

**What steps did you take and what happened:**
`storagePolicyName` is missing in the templates file [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/templates/cluster-template.yaml). 
We need to add 
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: VSphereMachineTemplate
metadata:
  name: '${CLUSTER_NAME}'
  namespace: '${NAMESPACE}'
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: '${VSPHERE_DATACENTER}'
      datastore: '${VSPHERE_DATASTORE}'
      diskGiB: 25
      folder: '${VSPHERE_FOLDER}'
      memoryMiB: 8192
      network:
        devices:
        - dhcp4: true
          networkName: '${VSPHERE_NETWORK}'
      numCPUs: 2
      resourcePool: '${VSPHERE_RESOURCE_POOL}'
      server: '${VSPHERE_SERVER}'
      storagePolicyName: '${VSPHERE_STORAGE_POLICY}'       <------------- add this field here
      template: '${VSPHERE_TEMPLATE}'
```

/assign

### PR DESCRIPTION
**Pull request by AartiJivrajani**
**What this PR does / why we need it**:
The cluster-template.yaml was missing the recently added field storagePolicyName.

 EDIT: Based on the comments below, this PR deletes the `cluster-template.yaml` and adds documentation around creating user-generated templates. 

**Which issue(s) this PR fixes**:
Fixes #1245 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by gab-satchi** [comment]
I think this `templates/cluster-template.yaml` file should just be deleted. It doesn't get used by anything and it may have been introduced by mistake

**Comment by AartiJivrajani** [comment]
@gab-satchi I see! Shall I go ahead and delete the file then?

**Comment by srm09** [comment]
@AartiJivrajani Along with deleting the file, we should update the `development.md` file to add a line or two around generating custom cluster templates using `make dev-flavors` command.

**Comment by gab-satchi** [comment]
/retitle clean up cluster-template and docs update

**Review by yastij — APPROVED** [review]
/lgtm

**Pull request merged**
