### PR TITLE
Skipping clusterctl upgrade tests

### PR DESCRIPTION
**Pull request by srm09**
Signed-off-by: Sagar Muchhal <muchhals@vmware.com>

**What this PR does / why we need it**:
This patch temporarily disables clusterctl upgrade tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # n/a

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by yastij — APPROVED** [review]
/approve
/lgtm

**Review by yastij — APPROVED** [review]
/lgtm

**Comment by fabriziopandini** [comment]
@srm09 @yastij let me know if there is something we can do to restore those tests, they could provide an important signal...

**Comment by randomvariable** [comment]
Same. Would be good to have known why in a TODO comment or something.

**Pull request merged**
