### PR TITLE
📖 Document backport policy

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Thanks for clarifying this!

/lgtm

**Review by chrischdi — COMMENTED** [review]
/approve

/hold if others want to review.

**Comment by sbueringer** [comment]
Let's keep this open for a bit and then merge it if there are no objections

**Pull request merged**
