### PR TITLE
Remove unused var

### PR DESCRIPTION
**Pull request by enxebre**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by akutz** [comment]
/hold

Hi @enxebre,

Some of this is about to change in a PR I'm opening, so this PR will need to be rebased. However, I'm also curious as to the reasoning behind this PR.

**Comment by enxebre** [comment]
>However, I'm also curious as to the reasoning behind this PR.

Hey @akutz I just saw a variable that's never used within the function is being passed as a parameter unless I'm missing something

**Comment by akutz** [comment]
Hi @enxebre,

If you could resolve the conflicts, I am ready to approve this. Thanks!

**Comment by enxebre** [comment]
should be good now @akutz

**Comment by randomvariable** [comment]
@enxebre I think you need to rebase to pull in the e2e tests so we can get this merged.

**Comment by randomvariable** [comment]
This is extremely late @enxebre , so apologies.

Mopped this one up with others in #787 

/close

**Pull request closed without merging**
