### PR TITLE
bump creation timeout to avoid flakes

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**: This PR bumps the creation timeout to absorb the flakes seen on e2e jobs. this should rule out the scenario where machines get stuck indefinitely 

**Which issue(s) this PR fixes** : Fixes #

**Special notes for your reviewer**:

/assign @akutz 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yastij** [comment]
closing this as the timeout bump was merged in another PR

**Comment by akutz** [comment]
Hi @yastij,

I think you should re-open this and bump the timeout to 20min as timeouts are still occurring. I'd also be interested to find out what CAPA's TTL for cluster creation is.

**Comment by yastij** [comment]
@vincepri or @detiber might now for aws

**Comment by detiber** [comment]
We're not currently using the new e2e framework, so getting a equivalent ttl for cluster creation might not match up appropriately. We have quite a few different timeouts that are inter-related and we're seeing flakes in our e2es, so not sure I can help give much guidance at this time :(

**Pull request closed without merging**
