### PR TITLE
[release-1.9] 📖 Drop direct link to OVA in ignition.md

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Synced with the same file on >= release-1.0
This should fix the remaining broken links

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Let's ignore codecov for this PR

/assign @chrischdi

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
Push forced to verify the codecov action is gone. Need another lgtm

**Pull request merged**
