### PR TITLE
📖 Remove v1alpha4 roadmap

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
I think it would make sense to drop this document as it was only for v1alpha4 and I think it doesn't provide a lot of value (also not sure how outdated it is).

My take is the following:
* [x] remove the CSI fields from the `VSphereClusterSpec` in favour of CRS
  * I think we didn't have fields for CSI 
* [x] remove the CPI fields from the `VSphereClusterSpec` in favour of CRS
  * CloudProviderConfiguration has been removed in v1alpha4  
* [x] move away from `ObjectReference`
  * Only usage now is for bootstrapRef but I assume this aligns to core CAPI
* [x] remove the HAProxy support (`LoadBalancerRef`, `HAProxyLoadBalancer` etc..)
  * As far as I can tell it is done. Will follow-up with an issue to consider deprecating contrib/haproxy  
* [x] introduce `Failure Domains` support
* [x] remove the `insecure` field in favour of the `thumbprint` field
* [x] remove `PreferredAPIServerCIDR`: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2092

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
@yastij @randomvariable @srm09 Does my take my sense to you (see PR description). What is the state on `PreferredAPIServerCIDR`? As far as I can tell the field is neither deprecated nor removed even in v1beta1. So I assume we decided to keep it.

**Comment by randomvariable** [comment]
I will have to defer to other maintainers, but otherwise
/lgtm

**Comment by sbueringer** [comment]
@randomvariable I moved the discussion around `PreferredAPIServerCIDR` to a separate issue (https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2092)

**Pull request merged**
