### PR TITLE
🌱 Use Ubuntu 22.04 for e2e tests

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #2252

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/approve
/lgtm

/hold

For pending e2e tests

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
CI green

/hold cancel

**Pull request merged**
