### PR TITLE
[WIP]README about flavors

### LINKED ISSUE #1457: Add README about flavors
/kind feature

There is no  README about what is the role of flavors in cluster-api-provider-vsphere and what all flavors are available.

This can be used as a reference.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/flavors/README.md

/help
/good-first-issue

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sayantani11**
**What this PR does / why we need it**:
Adds a readme about flavors 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1457 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
README about flavors
```

### CODE REVIEW

**Comment by srm09** [comment]
@aartij17 @geetikabatra Would you be able to guide @sayantani11 with this one?

**Comment by sayantani11** [comment]
Hey @geetikabatra can I get some help related to this?

**Comment by geetikabatra** [comment]
@sayantani11 Sure! Where are you stuck at?

**Comment by sayantani11** [comment]
> @sayantani11 Sure! Where are you stuck at?

I am stuck with the setting up part of Tilt. Let's continue the details on slack?

**Pull request closed without merging**
